### PR TITLE
update instructions for creating a new branch name to preferred practice

### PR DESCRIPTION
**Pull request by ctb**
- [x] Is it mergeable?
- [x] Did it pass the tests?
- [x] If it introduces new functionality in scripts/ is it tested?
  Check for code coverage with `make clean diff-cover`
- [x] Is it well formatted? Look at `make pep8`, `make diff_pylint_report`,
  `make cppcheck`, and `make doc` output. Use `make format` and manual
  fixing as needed.
- [x] Did it change the command-line interface? Only additions are allowed
  without a major version increment. Changing file formats also requires a
  major version number increment.
- [x] Is it documented in the ChangeLog?
  http://en.wikipedia.org/wiki/Changelog#Format
- [x] Was a spellchecker run on the source code and documentation after
  changes were made?
- [x] Is the Copyright year up to date?

### CODE REVIEW

**Comment by ctb** [comment]
Jenkins, please test this.

**Comment by ctb** [comment]
Jenkins, test this please.

**Comment by ctb** [comment]
Jenkins, test this please.

**Comment by ctb** [comment]
Ready for review & merge, @mr-c.

**Comment by mr-c** [comment]
There was an error in the Jenkins `make doc` output that wasn't visible to people using the regular dev setup. I've fixed the source of that error and unified the Jenkins build script & `make install-dep`

**Comment by mr-c** [comment]
I've rebased upon master.

**Comment by mr-c** [comment]
LGTM. Since I added a couple commits of mine own can @camillescott or @luizirber review & merge this?

**Comment by luizirber** [comment]
LGTM (I was confused because `doc/requirements.txt` wasn't added, but then checked and it was already on the repo).

**Pull request merged**
