### PR TITLE
[WIP] Support a man page make target

### LINKED ISSUE #619: generate unix manual ("man") pages from the docs

### PR DESCRIPTION
**Pull request by standage**
Supersedes #838. This may or may not be worth pursuing. If we do, we'll have to consider installation as well as trimming down on the excessive amount of release notes included.

Closes #619.

- [ ] Is it mergeable?
- [ ] `make test` Did it pass the tests?
- [ ] `make clean diff-cover` If it introduces new functionality in
  `scripts/` is it tested?
- [ ] `make format diff_pylint_report cppcheck doc pydocstyle` Is it well
  formatted?
- [ ] Did it change the command-line interface? Only backwards-compatible
  additions are allowed without a major version increment. Changing file
  formats also requires a major version number increment.
- [ ] For substantial changes or changes to the command-line interface, is it
  documented in `CHANGELOG.md`? See [keepachangelog](http://keepachangelog.com/)
  for more details.
- [ ] Was a spellchecker run on the source code and documentation after
  changes were made?
- [ ] Do the changes respect streaming IO? (Are they
  tested for streaming IO?)

### CODE REVIEW

**Comment by betatim** [comment]
Do you know anyone who actually reads man pages for python projects like this? Asking because it would never really cross my mind to ask man for a project like khmer.

**Comment by standage** [comment]
> Do you know anyone who actually reads man pages for python projects like this?

Nope. There was a stale open pull request on a fork we do not have access to, so rather than trying to revive it I figured I'd move it here for consideration. It was certainly simple enough.

@mr-c mentioned that Debian packaging requirements have been satisfied, so this may very well be worth closing.

**Comment by betatim** [comment]
I'd vote to not add this if we don't need to.

**Comment by standage** [comment]
I concur. I'll close this by Monday unless anyone protests.

**Pull request closed without merging**
