### PR TITLE
Rename counting_hash and hashbits at Python layer

### LINKED ISSUE #872: Rename counting_hash and hashbits at Python layer
I suggest counting_table and/or bytegraph instead of counting_hash, and bitgraph instead of hashbits. (@mr-c has already renamed stopped using 'hash' in our scripts and docs).

counting_table could default to bigcounts=yes, bytegraph could default to bigcounts=no, but otherwise be the same structure.

Reason: I found it silly to be using counting_hash in my VanBUG talk when I was talking about graphs.

### PR DESCRIPTION
**Pull request by mr-c**
Fixes #872

### CODE REVIEW

**Comment by mr-c** [comment]
Jenkins, retest this please

**Comment by ctb** [comment]
Also see #1032.

**Comment by mr-c** [comment]
- [ ] Is it mergeable?
- [ ] Did it pass the tests?
- [ ] If it introduces new functionality in scripts/ is it tested?
  Check for code coverage with `make clean diff-cover`
- [ ] Is it well formatted? Look at `make pep8`, `make diff_pylint_report`,
  `make cppcheck`, and `make doc` output. Use `make format` and manual
  fixing as needed.
- [ ] Did it change the command-line interface? Only additions are allowed
  without a major version increment. Changing file formats also requires a
  major version number increment.
- [ ] Is it documented in the ChangeLog?
  http://en.wikipedia.org/wiki/Changelog#Format
- [ ] Was a spellchecker run on the source code and documentation after
  changes were made?
- [ ] Is the Copyright year up to date?

**Comment by ctb** [comment]
What script/approach did you use for renaming?

**Comment by mr-c** [comment]
@ctb I used

```
ls scripts/*.py tests/*.py sandbox/*.py tests/*.py khmer/*.py oxli/*.py | xargs sed -i 's/CountingHash/CountGraph/g'
```

Followed by `git diff` review and lots of testing.

**Comment by mr-c** [comment]
Jenkins, retest this please

**Comment by ctb** [comment]
thanks!

**Comment by mr-c** [comment]
@ctb @luizirber Ready for review & merge

**Comment by ctb** [comment]
My thoughts --

* `countinggraph` is annoyingly long and `graph` would be an equally unambiguous choice in many sccripts - c.f. `abundance-dist-single.py` for an example.  What do you think about just using `graph`?
* do we want to change the print statements? e.g. see `Saving k-mer counting table filename` in filter-abund-single.py
* there are a bunch of places in older scripts/ code where we're using htable; fix? It's not always just nodegraph, though.

See #1212 for some additional suggested changes.

**Comment by mr-c** [comment]
Jenkins, retest this please

**Comment by mr-c** [comment]
Re: 
* `countinggraph` is annoyingly long and `graph` would be an equally unambiguous choice in many sccripts - c.f. `abundance-dist-single.py` for an example.  What do you think about just using `graph`?

Did you mean `countgraph`? That would be find by me.

**Comment by mr-c** [comment]
Does that mean all `--savetable`s need to become `--savegraph` as well?

**Comment by ctb** [comment]
On Thu, Aug 06, 2015 at 03:09:43PM -0700, Michael R. Crusoe wrote:
> Does that mean all `--savetable`s need to become `--savegraph` as well?

They did when we switched away from savehash... so I guess so.

**Comment by ctb** [comment]
On Thu, Aug 06, 2015 at 02:57:13PM -0700, Michael R. Crusoe wrote:
> Re: 
> * `countinggraph` is annoyingly long and `graph` would be an equally unambiguous choice in many sccripts - c.f. `abundance-dist-single.py` for an example.  What do you think about just using `graph`?
> 
> Did you mean `countgraph`? That would be find by me.

sure.

**Comment by mr-c** [comment]
@ctb ready for review & merge

My apologies to everyone else who has to merge after this

**Comment by mr-c** [comment]
Jenkins, retest this please

**Comment by ctb** [comment]
updating with master.

**Comment by ctb** [comment]
@mr-c see 5400837 - if it looks good, please go ahead and merge. Thx!

**Comment by mr-c** [comment]
Looks great, thanks!

**Pull request merged**
