### PR TITLE
Add depsy badge

### PR DESCRIPTION
**Pull request by mr-c**

### CODE REVIEW

**Comment by mr-c** [comment]
- [ ] Is it mergeable?
- [ ] Did it pass the tests?
- [ ] If it introduces new functionality in scripts/ is it tested?
  Check for code coverage with `make clean diff-cover`
- [ ] Is it well formatted? Look at `make pep8`, `make diff_pylint_report`,
  `make cppcheck`, and `make doc` output. Use `make format` and manual
  fixing as needed.
- [ ] Did it change the command-line interface? Only additions are allowed
  without a major version increment. Changing file formats also requires a
  major version number increment.
- [ ] Is it documented in the ChangeLog?
  http://en.wikipedia.org/wiki/Changelog#Format
- [ ] Was a spellchecker run on the source code and documentation after
  changes were made?
- [ ] Do the changes respect streaming IO? (Are they
  tested for streaming IO?)
- [ ] Is the Copyright year up to date?

**Comment by mr-c** [comment]
Ping @camillescott for review & merge. Thank you!

**Comment by mr-c** [comment]
Hello @ctb  @luizirber @camillescott @standage I'm cleaning up old branches for merging or deleting.

Shall I merge this PR to add the Depsy badge to the Readme?

**Comment by ctb** [comment]
thx @mr-c

**Comment by mr-c** [comment]
Thank-ee

On Sun, May 8, 2016 at 3:40 PM, C. Titus Brown <notifications@github.com>
wrote:

> thx @mr-c <https://github.com/mr-c>
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/dib-lab/khmer/pull/1326#issuecomment-217719191>
>



-- 
Michael R. Crusoe                          michael.crusoe@gmail.com
Community Engineer                 Common Workflow Language project
https://impactstory.org/u/0000-0002-2961-9670   +32 (0) 2 808 25 58
                                                    +1 480 627 9108

**Pull request merged**
