### PR TITLE
Remove many unused/unnecessary functions.

### PR DESCRIPTION
**Pull request by ctb**
Eliminates a wide variety of unused/untested/unneeded and sometimes broken functions.

- [x] Is it mergeable?
- [x] Did it pass the tests?
- [x] If it introduces new functionality in scripts/ is it tested?
  Check for code coverage with `make clean diff-cover`
- [x] Is it well formatted? Look at `make pep8`, `make diff_pylint_report`,
  `make cppcheck`, and `make doc` output. Use `make format` and manual
  fixing as needed.
- [x] Did it change the command-line interface? Only additions are allowed
  without a major version increment. Changing file formats also requires a
  major version number increment.
- [x] Is it documented in the ChangeLog?
  http://en.wikipedia.org/wiki/Changelog#Format
- [x] Was a spellchecker run on the source code and documentation after
  changes were made?
- [x] Do the changes respect streaming IO? (Are they
  tested for streaming IO?)
- [x] Is the Copyright year up to date?

### CODE REVIEW

**Comment by ctb** [comment]
Ready for review and merge @luizirber.

**Comment by ctb** [comment]
@mr-c merging this one might give you some good feels if you're so inclined :)

**Comment by mr-c** [comment]
@ctb It would be my pleasure. Are you all using the `squash and merge` GitHub feature, or just plain merges?

**Comment by ctb** [comment]
On Sun, May 08, 2016 at 06:12:33AM -0700, Michael R. Crusoe wrote:
> @ctb It would be my pleasure. Are you all using the `squash and merge` GitHub feature, or just plain merges?

I still maintain that it doesn't matter but if you want me to squash & merge
I can do so this instant.  Shall I?

**Comment by mr-c** [comment]
This is a GUI feature, no squashing by the submitter; I don't care either way, was just checking to see what decision you all had made :-)

screenshot 2016-05-08 at 15 16 31

**Comment by ctb** [comment]
Ahh! I hadn't even seen that. It's fine by me.

**Comment by mr-c** [comment]
Nothing feels as good as deleting code :-)

**Comment by ctb** [comment]
w00t thx

**Pull request merged**
