### PR TITLE
Support for different read parsers using functor templates

### PR DESCRIPTION
**Pull request by standage**
Working branch. Will replace the `IParser` abstract class with a concrete class `ReadParser`. Imprinting reads in various formats (Fast[a,q] and BAM, initiallly) will be delegated by functor classes, which are declared in the `ReadParser` class using templates.
- [ ] Is it mergeable?
- [ ] `make test` Did it pass the tests?
- [ ] `make clean diff-cover` If it introduces new functionality in
  `scripts/` is it tested?
- [ ] `make format diff_pylint_report cppcheck doc pydocstyle` Is it well
  formatted?
- [ ] Did it change the command-line interface? Only additions are allowed
  without a major version increment. Changing file formats also requires a
  major version number increment.
- [ ] Is it documented in the `ChangeLog`?
  http://en.wikipedia.org/wiki/Changelog#Format
- [ ] Was a spellchecker run on the source code and documentation after
  changes were made?
- [ ] Do the changes respect streaming IO? (Are they
  tested for streaming IO?)
- [ ] Is the Copyright year up to date?

### CODE REVIEW

**Comment by standage** [comment]
Retest this please jenkins

**Comment by standage** [comment]
I've gone through and added the needed templating to support parsing different data formats. Everything appears to be ok-ish on the C++ side: it certainly compiles fine. But there's a problem when Python links to the library.

```
ImportError while importing test module '/Users/standage/Software/khmer/tests/test_countgraph.py'.
Original error message:
'dlopen(/Users/standage/Software/khmer/khmer/_khmer.cpython-35m-darwin.so, 2): Symbol not found: __ZN5khmer12read_parsers11FastxReaderC1ERS1_
  Referenced from: /Users/standage/Software/khmer/khmer/_khmer.cpython-35m-darwin.so
  Expected in: flat namespace
 in /Users/standage/Software/khmer/khmer/_khmer.cpython-35m-darwin.so'
Make sure your test modules/packages have valid Python names.
```

The function name looks like a namespace expansion. Perhaps I haven't declared or used the namespaces correctly throughout? Any ideas @camillescott @luizirber?

**Comment by standage** [comment]
Some potential issues, discussed with @camillescott:

- forward declarations to templated classes creates problems
- explicit declaration of templated functions (as opposed to fully templated classes) should potentially be moved to header file, or maybe even removed

Fiddling with these for a couple of hours didn't render any progress. :-(

**Comment by betatim** [comment]
I can take a look later today/Friday if you want to?

**Comment by standage** [comment]
Yeah, but no hurry. @camillescott and I took a long look the other day, and we're baffled. I'm considering moving the entire ReadParser implementation to the header and dumping `read_parsers.cc`. Unless you're able to shed some light on the situation, that's probably where I'll pick up with this tomorrow.

**Comment by standage** [comment]
Superseded by #1597.

**Pull request closed without merging**
