### PR TITLE
Fix problems with using pointers to deallocated strings.

### LINKED ISSUE #1406: Test failures on ~recent Ubuntu (running on EC2)
We've been getting test errors on Ubuntu EC2 instances... see [errors.txt](https://github.com/dib-lab/khmer/files/367846/errors.txt) for details. These are in

```
test_num_reads_truncated
test_read_truncated
test_read_pair_iterator_in_error_mode_xfail
```

Looks like some sort of string corruption - I've seen this kind of thing when we're using `.c_str()` on std::string objects and keeping the pointer after the object goes out of scope and gets deallocated; it seems like different versions of glibc have different behavior here. Just a thought.

platform details:

```
% uname -a
Linux gps 4.2.0-30-generic #35-Ubuntu SMP Fri Feb 19 13:52:26 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
```

using AMI for ubuntu 15.10
```
ubuntu/images/hvm/ubuntu-wily-15.10-amd64-server-20160222 (ami-05384865)
```

### PR DESCRIPTION
**Pull request by ctb**
Fixed #1406.

- [x] Is it mergeable?
- [x] `make test` Did it pass the tests?
- [x] `make clean diff-cover` If it introduces new functionality in
  `scripts/` is it tested?
- [x] `make format diff_pylint_report cppcheck doc pydocstyle` Is it well
  formatted?
- [x] Did it change the command-line interface? Only additions are allowed
  without a major version increment. Changing file formats also requires a
  major version number increment.
- [x] Is it documented in the `ChangeLog`?
  http://en.wikipedia.org/wiki/Changelog#Format
- [x] Was a spellchecker run on the source code and documentation after
  changes were made?
- [x] Do the changes respect streaming IO? (Are they
  tested for streaming IO?)
- [x] Is the Copyright year up to date?

### CODE REVIEW

**Comment by ctb** [comment]
Ready for review (and probably merge). I have verified that all of tests pass on the relevant Ubuntu/glibc platform (see #1406).

**Comment by ctb** [comment]
The code coverage decreases are due to the additions of lines in already-uncovered blocks. I'm -0 on adding coverage of those blocks in this PR b/c it would delay the merge, but welcome other opinions - the bugs being fixed here are not critical to fix.

**Comment by standage** [comment]
@ctb Am I correct in thinking this was an issue of scoping? Was the `std::string` being deallocated as soon as it left each corresponding code block?

**Comment by ctb** [comment]
Yes, exactly!!

I looked through all the catch statements in the CPython interface and
tried to fix them all.

**Comment by standage** [comment]
Ok, LGTM!

**Pull request merged**
