### PR TITLE
Add -b to abundance-dist.py

### PR DESCRIPTION
**Pull request by drtamermansour**
abundance-dist.py does not count k-mers past 255 by default which is as if you used [-b] in  abundance-dist-single.py. As a k-mer counting package, I think this function should be available. 
The problem here is we are changing the default behavir of the script. I you think that we should keep the change, I will work on adding a test.

### CODE REVIEW

**Comment by ctb** [comment]
On Sat, Apr 04, 2015 at 03:56:57PM -0700, Tamer Mansour wrote:
> abundance-dist.py does not count k-mers past 255 by default.

It should; are you sure about this?

**Comment by mr-c** [comment]
According to my reading of the source @drtamermansour is correct. Neither Python nor the C++ library default to using bigcount on new countinghashes.

**Comment by ctb** [comment]
On Sun, Apr 05, 2015 at 04:31:03AM -0700, Michael R. Crusoe wrote:
> According to my reading of the source @drtamermansour is correct. Neither Python nor the C++ library default to using bigcount on new countinghashes.

OK.  Then this issue is a good idea :)

**Comment by ctb** [comment]
@drtamermansour @bocajnotnef could one of you add a test to this? then I can review & merge.

**Comment by drtamermansour** [comment]
@bocajnotnef <https://github.com/bocajnotnef>  are you interested??

**Comment by bocajnotnef** [comment]
Sure, but I won't be able to get to it until later tonight, most likely

**Comment by ctb** [comment]
no hurry, just want someone to finish it before 2.0.

**Comment by bocajnotnef** [comment]
retest this please, Jenkins

**Comment by bocajnotnef** [comment]
@ctb tests added in #1067--sorry for the shuffle. Didn't realize this branch was in @drtamermansour's repo. Migrated it to the lab's.

**Comment by ctb** [comment]
Tests failed?

**Comment by ctb** [comment]
Oh, I see.  Next time you might as well close the PR :)

**Pull request closed without merging**
