### PR TITLE
Small optimization to median_at_least

### PR DESCRIPTION
**Pull request by camillescott**
This tiny optimization addresses @ctb's comment about reducing the number of branches.

### CODE REVIEW

**Comment by camillescott** [comment]
- [x] Is it mergeable?
   - [x] Did it pass the tests?
   - [x] If it introduces new functionality in scripts/ is it tested?
     Check for code coverage with `make clean diff-cover`
   - [x] Is it well formatted? Look at `make pep8`, `make diff_pylint_report`,
     `make cppcheck`, and `make doc` output. Use `make format` and manual
     fixing as needed.
   - [x] Did it change the command-line interface? Only additions are allowed
     without a major version increment. Changing file formats also requires a
     major version number increment.
   - [ ] Is it documented in the ChangeLog?
     http://en.wikipedia.org/wiki/Changelog#Format
   - [x] Was a spellchecker run on the source code and documentation after
     changes were made?

**Comment by camillescott** [comment]
@ctb review and merge whenever :)

**Comment by ctb** [comment]
LGTM - @camillescott check out my in-line comments; if they're ok with you, then merge!

**Comment by camillescott** [comment]
+1 on comments, merging

**Pull request merged**
