### PR TITLE
Add enchant to package manager install instructions

### PR DESCRIPTION
**Pull request by standage**
- [x] Is it mergeable?
- [x] `make test` Did it pass the tests?
- [x] `make clean diff-cover` If it introduces new functionality in
  `scripts/` is it tested?
- [x] `make format diff_pylint_report cppcheck doc pydocstyle` Is it well
  formatted?
- [x] Did it change the command-line interface? Only additions are allowed
  without a major version increment. Changing file formats also requires a
  major version number increment.
- [x] Is it documented in the `ChangeLog`?
  http://en.wikipedia.org/wiki/Changelog#Format
- [x] Was a spellchecker run on the source code and documentation after
  changes were made?
- [x] Do the changes respect streaming IO? (Are they
  tested for streaming IO?)
- [x] Is the Copyright year up to date?

### CODE REVIEW

**Comment by standage** [comment]
Ready for review

**Comment by betatim** [comment]
🔄🎸

(rebase me please)

Surprised to see you did your work in a branch in this repo, on other projects people have their stuff in their forks. So normally I can't take care of trivial rebases like this one, but here I could. For now I won't. What do people here normally do?

**Comment by ctb** [comment]
We don't require rebasing; please see: https://github.com/dib-lab/khmer/issues/660. This was apparently added to the developer documentation at some point but I can't find it :).

Lab policy is that members of the org do their development in branches w/in the repo. If there's a strong reason to change that, create an issue and we can discuss :)

**Comment by betatim** [comment]
> We don't require rebasing; please see: #660. This was apparently added to the developer documentation at some point but I can't find it :).

How do you fix simple conflicts like in this PR (just needs the Changelog stuff moving)? Haven't read all of #660, it seems to discuss **squashing** commits, which can be a bit counter productive.

> Lab policy is that members of the org do their development in branches w/in the repo. If there's a strong reason to change that, create an issue and we can discuss :)

I will update my habits *hidesallhisbranchesinhisforksomehow*

What I wanted to know though is can I take this branch, rebase it (or do what ever you do to fix the conflict) and then merge it or wait for @standage to do that himself?

**Comment by ctb** [comment]
On Mon, Aug 29, 2016 at 07:09:15AM -0700, Tim Head wrote:
> > We don't require rebasing; please see: #660. This was apparently added to the developer documentation at some point but I can't find it :).
> 
> How do you fix simple conflicts like in this PR (just needs the Changelog stuff moving)? Haven't read all of #660, it seems to discuss **squashing** commits, which can be a bit counter productive.
> 
> > Lab policy is that members of the org do their development in branches w/in the repo. If there's a strong reason to change that, create an issue and we can discuss :)
> 
> I will update my habits *hidesallhisbranchesinhisforksomehow*
> 
> What I wanted to know though is can I take this branch, rebase it (or do what ever you do to fix the conflict) and then merge it or wait for @standage to do that himself?

Generally => @standage fixes.

**Comment by ctb** [comment]
(You can also fix conflicts by editing the files and making another commit,
you know :)

**Comment by standage** [comment]
Ready for review/merge once the build checks out.

**Comment by standage** [comment]
Retest this please jenkins

**Comment by betatim** [comment]
🌠 two in one day!

**Pull request merged**
