### PR TITLE
Updates to documentation

### PR DESCRIPTION
**Pull request by standage**
- [x] Is it mergeable?
- [x] `make test` Did it pass the tests?
- [x] `make clean diff-cover` If it introduces new functionality in
  `scripts/` is it tested?
- [x] `make format diff_pylint_report cppcheck doc pydocstyle` Is it well
  formatted?
- [x] Did it change the command-line interface? Only additions are allowed
  without a major version increment. Changing file formats also requires a
  major version number increment.
- [x] Is it documented in the `ChangeLog`?
  http://en.wikipedia.org/wiki/Changelog#Format
- [x] Was a spellchecker run on the source code and documentation after
  changes were made?
- [x] Do the changes respect streaming IO? (Are they
  tested for streaming IO?)
- [x] Is the Copyright year up to date?

### CODE REVIEW

**Comment by standage** [comment]
Working on #1373.

**Comment by standage** [comment]
Ready for review and merge @ctb (or anyone else)

**Comment by standage** [comment]
Closes #1373.

**Comment by standage** [comment]
Jenkins retest this please.

**Comment by ctb** [comment]
Again, a bunch of unrelated whitespace changes showing up - can you fix your editor and/or do them in separate PRs?

**Comment by ctb** [comment]
Can you update w/whitespace branch, pls? All the changes look good to me - update & I can merge.

**Comment by standage** [comment]
Updated.

**Pull request merged**
