### PR TITLE
PEP8 fixes

### PR DESCRIPTION
**Pull request by standage**
The last PR introduced some PEP8 violations that I missed due to CI issues. This PR fixes those, and makes the `pep8` target a bit less verbose.

----------

- [x] Is it mergeable?
- [x] `make test` Did it pass the tests?
- [x] `make clean diff-cover` If it introduces new functionality in
  `scripts/` is it tested?
- [x] `make format diff_pylint_report cppcheck doc pydocstyle` Is it well
  formatted?
- [x] Did it change the command-line interface? Only additions are allowed
  without a major version increment. Changing file formats also requires a
  major version number increment.
- [x] Is it documented in the `ChangeLog`?
  http://en.wikipedia.org/wiki/Changelog#Format
- [x] Was a spellchecker run on the source code and documentation after
  changes were made?
- [x] Do the changes respect streaming IO? (Are they
  tested for streaming IO?)
- [x] Is the Copyright year up to date?

### CODE REVIEW

**Comment by standage** [comment]
And THANKFULLY the time I put in on Jenkins today paid off it looks like!

Ready for review and merge @betatim @ctb @luizirber @camillescott

**Comment by betatim** [comment]
LGTM

**Comment by betatim** [comment]
(The new "normal" for coverage is ~77% since #1421 got merged.)

Merging.

**Comment by betatim** [comment]
Thanks for pepping things up 😀

**Comment by standage** [comment]
#rimshot

**Pull request merged**
