### PR TITLE
[WIP] Add KarpRabin hash iterator

### LINKED ISSUE #1616: Explore @lemire's rolling hash function as an alternative for Counttable
See https://github.com/lemire/rollinghashcpp/blob/master/example.cpp

Should be much faster than murmurhash.

### PR DESCRIPTION
**Pull request by betatim**
Fixes #1616 

Exploring how to add RabinKarp hashing

- [ ] Is it mergeable?
- [ ] `make test` Did it pass the tests?
- [ ] `make clean diff-cover` If it introduces new functionality in
  `scripts/` is it tested?
- [ ] `make format diff_pylint_report cppcheck doc pydocstyle` Is it well
  formatted?
- [ ] Did it change the command-line interface? Only backwards-compatible
  additions are allowed without a major version increment. Changing file
  formats also requires a major version number increment.
- [ ] For substantial changes or changes to the command-line interface, is it
  documented in `CHANGELOG.md`? See [keepachangelog](http://keepachangelog.com/)
  for more details.
- [ ] Was a spellchecker run on the source code and documentation after
  changes were made?
- [ ] Do the changes respect streaming IO? (Are they
  tested for streaming IO?)

### CODE REVIEW

**Comment by betatim** [comment]
For the moment this is stalled because there is no `reverse_update` for Rabin Karp. We need to remove the last base and prepend a new base when computing the reverse complement in the iterator. `CyclingHash` supports this but `RabinKarp` doesn't :(

```
fwd: CGGTA
rev: TACCG
```
we'd like to update the hash from `h(ACCG)` to `h(TACC)`. Will switch to CyclingHash I think.

**Comment by betatim** [comment]
A related question, do we want to add a new type `CycleCounttable` or replace the use of murmur hash? I think at least at the python level we should not add a new type but handle it via a `__init__` argument if we don't straight up replace murmurhash.

**Comment by ctb** [comment]
agree with not adding a new type, i.e. handling it with __init__.  I think
we will want murmurhash as an option tho, since it's being used in other
places (the minhash world).

**Comment by ctb** [comment]
we could also provide a single stranded option? or keep both strands
around in the iterator?

**Comment by luizirber** [comment]
FYI: I was playing with something similar in the MurmurHashKmerIterator: https://github.com/dib-lab/khmer/compare/refactor/murmur_iterator

When I was benchmarking HLL `_revcomp` was by far what was taking more time to run (almost half of total runtime!), so the idea here is to update both the kmer being calculated and its revcomp base by base (instead of recalculating the revcomp for each kmer), and then calculate the hash value for both.

I had to change the implementation of `_hash_murmur_forward`  (because it was calling `_hash_murmur`, which always calls `_revcomp`...), and right now it is buggy (because I'm losing bases along the way? =P), but you can check the implementation here: https://github.com/dib-lab/khmer/compare/refactor/murmur_iterator#diff-8277863672a7ea5bfac461ec9cfea68dR282

**Comment by ctb** [comment]
On Thu, Feb 16, 2017 at 11:12:32AM -0800, Luiz Irber wrote:
> FYI: I was playing with something similar in the MurmurHashKmerIterator: https://github.com/dib-lab/khmer/compare/refactor/murmur_iterator

sounds good to me!

**Comment by betatim** [comment]
Thanks for the links. Computing both the forward and reverse hash of a kmer by adding and removing just one base to each is the goal, because as you say it uses a lot of CPU otherwise. And like you I have a bug somewhere right now :)

**Comment by ctb** [comment]
Abandoned now that #1792 is merged, I think.

**Pull request closed without merging**
