### PR TITLE
[WIP] Decontamination filter for khmer

### PR DESCRIPTION
**Pull request by brainstorm**
Hi @mr-c,

As promised, I've started to tackle issue #232. Just got started, I'm figuring out how khmer for now, so not much to see here yet (see XXX's), but I'll be iterating on this PR until it's ready for consumption.

- [x] Is it mergable
- [ ] Did it pass the tests?
- [ ] If it introduces new functionality in scripts/ is it tested?
  Check for code coverage.
- [x] Is it well formatted? Look at `pep8`/`pylint`, `cppcheck`, and
  `make doc` output. Use `autopep8` and `astyle -A10 --max-code-length=80`
  if needed.
- [ ] Is it documented in the Changelog?
- [x] Was spellcheck run on the source code and documentation after changes
  were made?

### CODE REVIEW

**Comment by bocajnotnef** [comment]
@brainstorm Status on this?

**Comment by bocajnotnef** [comment]
ok to test.

**Comment by mr-c** [comment]
@bocajnotnef Funny timing; I just wrote an email to Roman offline while on the plane.

**Comment by brainstorm** [comment]
I will try to pick it up again in some of the upcoming hackathons (either PyCon or Mozilla Sprint or both ;P).

**Comment by mr-c** [comment]
@brainstorm Huzzah!

**Pull request closed without merging**
