### PR TITLE
Mqf integration

### PR DESCRIPTION
**Pull request by shokrof**
- [x] Is it mergeable?
- [x] `make test` Did it pass the tests?
- [x] `make clean diff-cover` If it introduces new functionality in
  `scripts/` is it tested? No new functionality is added
- [ ] `make format diff_pylint_report cppcheck doc pydocstyle` Is it well
  formatted? 
      **Khmer source files are changed after running this command.**
- [x] Did it change the command-line interface? Only backwards-compatible
  additions are allowed without a major version increment. Changing file
  formats also requires a major version number increment. 
- [x] For substantial changes or changes to the command-line interface, is it
  documented in `CHANGELOG.md`? See [keepachangelog](http://keepachangelog.com/)
  for more details.
- [x] Was a spellchecker run on the source code and documentation after
  changes were made?
- [x] Do the changes respect streaming IO? (Are they
  tested for streaming IO?)

### CODE REVIEW

**Comment by ctb** [comment]
hi @shokrof how does this differ from #1855?

In general, you should update pull requests rather than opening new ones with the same or similar content. Let us know if you need some pointers ;)

**Comment by shokrof** [comment]
I made a mistake in the previous. I didn't start a new branch before integrating MQF in Khmer. So, the previous pull request contained commits that are not related to the integration, and they were causing problems.  
I created a new branch from the master, I cherry-picked the integration commits and made a new pull request. 
From now, I will update this pull request and won't open a new one.





Thanks for your patience, I may need some time to get used to your system.

**Comment by ctb** [comment]
gotcha! no worries ;)

**Comment by standage** [comment]
Thanks for the info, Mostafa!

If there is anything in particular you'd like preliminary feedback on, please let us know what and where. Otherwise, many of us will simply wait patiently until you post a message like "Ready for review!" or "Ready for final review!"

I'll be very excited if we can get the MQF working nicely with the other khmer internals. Thanks for your work on this!

**Comment by shokrof** [comment]
Hi Daniel,
Thanks for your kind words. 
I have one question.  Do I have to run "make format diff_pylint_report cppcheck doc pydocstyle"?
it changes many unrelated files.

Have a nice day,
Mostafa

**Comment by shokrof** [comment]
@ctb I cant keep my promise. I will start a new pull request from the new branch in dib-lab.
:)

**Comment by ctb** [comment]
I _think_ you could have edited the branches involved, FYI. but this is fine.

**Comment by standage** [comment]
> Do I have to run "make format diff_pylint_report cppcheck doc pydocstyle"? it changes many unrelated files.

You'll want to make sure the docs build ok with `make doc` but the other checks aren't critical. I'm actually trying to get our checklist updated in #1847, but review of these changes is still pending (cc @ctb).

**Pull request closed without merging**
