### PR TITLE
updated whats-new-2.0.rst

### PR DESCRIPTION
**Pull request by mr-c**
From the conversation at #1256

### CODE REVIEW

**Comment by mr-c** [comment]
- [ ] Is it mergeable?
- [ ] Did it pass the tests?
- [ ] If it introduces new functionality in scripts/ is it tested?
  Check for code coverage with `make clean diff-cover`
- [ ] Is it well formatted? Look at `make pep8`, `make diff_pylint_report`,
  `make cppcheck`, and `make doc` output. Use `make format` and manual
  fixing as needed.
- [ ] Did it change the command-line interface? Only additions are allowed
  without a major version increment. Changing file formats also requires a
  major version number increment.
- [ ] Is it documented in the ChangeLog?
  http://en.wikipedia.org/wiki/Changelog#Format
- [ ] Was a spellchecker run on the source code and documentation after
  changes were made?
- [ ] Do the changes respect streaming IO? (Are they
  tested for streaming IO?)
- [ ] Is the Copyright year up to date?

**Comment by mr-c** [comment]
@ctb This basically is the heart of the upcoming release notes. You can review it now or @camillescott can do so and I can reserve time for you to review before I release 2.0.

**Comment by ctb** [comment]
I'll try to get to it today or over the weekend.  I've already looked over
most of the differences so I think it's basically good :)

**Comment by ctb** [comment]
Thoughts on review --

--force-single on diginorm conflicts with --force_single on sample-reads-randomly. See @standage comment on this: https://github.com/dib-lab/khmer/pull/933#issuecomment-94997181.  I prefer force-single, but regardless of what we decide we should be consistent with at least this one option.

Under "New behavior", the text that occurs under "Mixed-pair sequence file format support" should be moved here and then referred to below.  Or something.  Regardless, the significant switch to support broken-paired behavior across the codebase should be mentioned in New Behavior somehow.

Under new behavior, we probably want to mention streaming I/O, no?  All the '-' behavior that we added?

Also under new behavior, the -M and -U options should be mentioned.  In fact, it looks like most of the text from incompatible changes should be moved up under new behavior, and only the switch from --min-tablesize to --max-tablesize needs to be mentioned in incompatible changes.

"it's helper" => "its helper"

**Comment by mr-c** [comment]
To match the existing script (since that is the current trend) I've picked `--force_single` over `--force-single` though my personal preference is for the later.

**Comment by mr-c** [comment]
@ctb ping

**Comment by ctb** [comment]
As in, ready for review?

--
Titus Brown, ctbrown@ucdavis.edu

**Comment by mr-c** [comment]
@ctb Yes, it is ready for your review of my latest changes. Do you feel that #1181 is satisfied by this PR?

**Comment by ctb** [comment]
I've made some changes; if they look good to you, we can merge. I think we probably will need more docs for #1181 so let's leave that open, but punt to > 2.0.

**Comment by mr-c** [comment]
Thanks; merged

**Pull request merged**
