### PR TITLE
Fix infinite loop in CountingHash gzipped IO

### PR DESCRIPTION
**Pull request by kdmurray91**
Addresses #1038 

- [x] Is it mergeable?
- [x] Did it pass the tests?
- [x] If it introduces new functionality in scripts/ is it tested?
  Check for code coverage with `make clean diff-cover`
- [x] Is it well formatted? Look at `make pep8`, `make diff_pylint_report`,
  `make cppcheck`, and `make doc` output. Use `make format` and manual
  fixing as needed.
- [x] Did it change the command-line interface? Only additions are allowed
  without a major version increment. Changing file formats also requires a
  major version number increment.
- [x] Is it documented in the ChangeLog?
  http://en.wikipedia.org/wiki/Changelog#Format
- [x] Was a spellchecker run on the source code and documentation after
  changes were made?
- [x] Is the Copyright year up to date?

### CODE REVIEW

**Comment by kdmurray91** [comment]
I'm going to add a test of this, but it will take a while to run and at least 2gb RAM. I'll use `@attr('huge')` to mark it. Is this OK?

**Comment by kdmurray91** [comment]
`Lines's stability is 87.83 and set mininum stability is 87.84`. Soooo close!

Also, ready for review @ctb @mr-c

**Comment by ctb** [comment]
LGTM on a skim, but I will leave for @mr-c to merge.  Note that we are in the middle of moving across the country so it may take a few weeks!

**Comment by kdmurray91** [comment]
Thanks, and good luck with the move :)

**Comment by mr-c** [comment]
@kdmurray91 'huge' is what 'linux' should have been named; can you rename the existing `@attr('linux')` to `huge`?

**Comment by kdmurray91** [comment]
No longer mergable, but as you're all moving I'll only rebase to fix the conflicts when you're ready to merge, which may take some time. Ping me when you're ready, and I'll rebase immediately :)

**Comment by ctb** [comment]
(We are also shifting to asking reviewers to make mergable on their own and
just merge, in cases where no other changes are needed.)

**Comment by mr-c** [comment]
- [ ] update linux->huge in Jenkins, Makefile (mr-c)

**Comment by mr-c** [comment]
also update instructions in docs

**Comment by kdmurray91** [comment]
yo @mr-c, just let me know as soon as you need anything from me on this. Happy to implement whatever else you need.

**Comment by mr-c** [comment]
@kdmurray91 The worst of the merges should be done for a while. It you want to make this mergeable that'd be appreciated :-)

**Comment by kdmurray91** [comment]
Good to go!

**Comment by mr-c** [comment]
LGTM, Thanks @kdmurray91 !

**Pull request merged**
