### PR TITLE
khmer directory cleanup

### LINKED ISSUE #1523: Let's delete IDEAS and TODO
...and move anything relevant to the issue tracker.

### PR DESCRIPTION
**Pull request by standage**
Trying to make it a bit easier to have a clean working directory. Considering making a `legacy` directory, but the only thing I would put in it at this point is the `setup.py.orig` file.

Before merging this, we should start new threads on the issue tracker for any TODOs or ideas that we want to keep "in memory".

Closes #1523.

- [x] Is it mergeable?
- [x] `make test` Did it pass the tests?
<strike>- [ ] `make clean diff-cover` If it introduces new functionality in
  `scripts/` is it tested?</strike>
<strike>- [ ] `make format diff_pylint_report cppcheck doc pydocstyle` Is it well
  formatted?</strike>
<strike>- [ ] Did it change the command-line interface? Only additions are allowed
  without a major version increment. Changing file formats also requires a
  major version number increment.</strike>
- [ ] Is it documented in the `ChangeLog`?
  http://en.wikipedia.org/wiki/Changelog#Format
<strike>- [ ] Was a spellchecker run on the source code and documentation after
  changes were made?</strike>
<strike>- [ ] Do the changes respect streaming IO? (Are they
  tested for streaming IO?)</strike>
<strike>- [ ] Is the Copyright year up to date?</strike>

### CODE REVIEW

**Comment by standage** [comment]
Ooh, there's also the legacy change log, which I'm about to replace. I think I will create a legacy directory.

**Comment by standage** [comment]
Huh, `setup.py.orig` must be a vestige. It's not under version control, and ignored with `*.orig` in `.gitignore`.

**Comment by standage** [comment]
Ready for review @ctb.

**Comment by betatim** [comment]
(the .orig files are side effects of resolving merge conflicts so they shouldn't be part of the repo)

**Comment by ctb** [comment]
The ideas and TODO are thoroughly out of date and can indeed just be deleted.

**Comment by betatim** [comment]
Merging ... don't think this qualifies for the new Changelog.

**Pull request merged**
