### PR TITLE
Put package version into `.info` files

### PR DESCRIPTION
**Pull request by kdmurray91**
As discussed in #1254

### CODE REVIEW

**Comment by kdmurray91** [comment]
Note this is a work in progress

**Comment by kdmurray91** [comment]
This is ready for review, I think.

- [ ] Is it mergeable?
- [ ] Did it pass the tests?
- [ ] If it introduces new functionality in scripts/ is it tested?
  Check for code coverage with `make clean diff-cover`
- [ ] Is it well formatted? Look at `make pep8`, `make diff_pylint_report`,
  `make cppcheck`, and `make doc` output. Use `make format` and manual
  fixing as needed.
- [ ] Did it change the command-line interface? Only additions are allowed
  without a major version increment. Changing file formats also requires a
  major version number increment.
- [ ] Is it documented in the ChangeLog?
  http://en.wikipedia.org/wiki/Changelog#Format
- [ ] Was a spellchecker run on the source code and documentation after
  changes were made?
- [ ] Do the changes respect streaming IO? (Are they
  tested for streaming IO?)
- [ ] Is the Copyright year up to date?

**Comment by kdmurray91** [comment]
jenkins, retest this please.

**Comment by kdmurray91** [comment]
Tests pass locally but for a CPython bug, though Jenkins seems to have chucked another wobbly.

**Comment by standage** [comment]
Tests pass after merging latest master.

**Comment by ctb** [comment]
@standage looks great! Please feel free to merge other people's commits ;).

**Comment by ctb** [comment]
thanks @kdmurray91

**Pull request merged**
