### PR TITLE
Catch error trying to delete tempdir on NFS

### PR DESCRIPTION
**Pull request by standage**
Issue #1402 manifests itself consistently on various HPC systems, both in the tests and when `trim-low-abund.py` is run interactively. I've had a few successful runs now by simply commenting out the code that deletes the temp directory at the end of the script. This PR puts a little bit of lipstick on that pig, making a backwards-compatible addition to the command-line interface. This (hopefully) isn't a permanent solution, but I don't have the time or interest to research the problem more thoroughly right now.

- [x] Is it mergeable?
- [x] `make test` Did it pass the tests?
- [x] `make clean diff-cover` If it introduces new functionality in
  `scripts/` is it tested?
- [x] `make format diff_pylint_report cppcheck doc pydocstyle` Is it well
  formatted?
- [x] Did it change the command-line interface? Only backwards-compatible
  additions are allowed without a major version increment. Changing file
  formats also requires a major version number increment.
- [x] For substantial changes or changes to the command-line interface, is it
  documented in `CHANGELOG.md`? See [keepachangelog](http://keepachangelog.com/)
  for more details.
- [x] Was a spellchecker run on the source code and documentation after
  changes were made?
- [x] Do the changes respect streaming IO? (Are they
  tested for streaming IO?)

### CODE REVIEW

**Comment by standage** [comment]
Ready for review!

**Comment by betatim** [comment]
In principle fine, do you understand what causes the removing of the directory to fail? The only alternative would be to catch the exception of `rmtree`, try again (and again (and again)).

According to google these `.nfs000` files get created when someone deletes a file that is still open by another process. So the 'real" solution will involve finding who that is (presumably somewhere in `khmer`).

**Comment by betatim** [comment]
My guess would be that https://github.com/dib-lab/khmer/blob/915069c89945ef2f6061ca7da3e64e4dc782ecf8/scripts/trim-low-abund.py#L419 is what might still have a file open when you want to remove the directory.

**Comment by standage** [comment]
> Do you want to do this in this PR or merge this and move on to other things? In which case I can take a look.

A proper fix would be nice, but I'm not eager to look into it myself.

**Comment by betatim** [comment]
Created #1603 to remind us to look into this.

While we wait for travis, @ctb (or others) any opinions on what we do with this "temporary" commandline argument? I think we can make it vanish again before the next release, so we don't run into the rule against changing the interface.

**Comment by ctb** [comment]
A simpler approach might be to put try/except around the rmtree and simply report the error without failing, no?

**Comment by standage** [comment]
> A simpler approach might be to put try/except around the rmtree and simply report the error without failing, no?

Great suggestion. Just updated and got my first successful `make test` on the Cabernet cluster for a long time. I usually have a dozen OSErrors from trim-low-abund tests to ignore.

Ready for a re-review and merge. @ctb @betatim

**Comment by standage** [comment]
@ctb See #1608.

**Pull request merged**
