### PR TITLE
Fixing failing master tests (#1171)

### PR DESCRIPTION
**Pull request by bocajnotnef**
Missed failing tests on one of my pulls; fixed here. See #1171 

- [x] Is it mergeable?
- [x] Did it pass the tests?
- [x] If it introduces new functionality in scripts/ is it tested?
  Check for code coverage with `make clean diff-cover`
- [x] Is it well formatted? Look at `make pep8`, `make diff_pylint_report`,
  `make cppcheck`, and `make doc` output. Use `make format` and manual
  fixing as needed.
- [x] Did it change the command-line interface? Only additions are allowed
  without a major version increment. Changing file formats also requires a
  major version number increment.
- [x] Is it documented in the ChangeLog?
  http://en.wikipedia.org/wiki/Changelog#Format
- [x] Was a spellchecker run on the source code and documentation after
  changes were made?
- [x] Is the Copyright year up to date?

### CODE REVIEW

**Comment by bocajnotnef** [comment]
Linux build passing http://ci.ged.msu.edu/job/khmer-pullrequest/label=linux/2599/

**Comment by bocajnotnef** [comment]
@camillescott @mr-c fix done.

**Comment by ctb** [comment]
Please go back through the checklist and pay attention to what you're checking off :). Then fix it, and I will merge.

**Comment by bocajnotnef** [comment]
There's no changelog entry--I figured it would be superfluous; the latest
entry is from the merge that introduced these problems.

**Comment by ctb** [comment]
Hmm. OK, well, if you don't want us to flag that on review, you should mention it somewhere ;).

**Comment by bocajnotnef** [comment]
Fair point.

Thanks!

**Pull request merged**
