### PR TITLE
update the diginorm documentation

### PR DESCRIPTION
**Pull request by ctb**
Deals with #1073, and changes introduced by in #1010 and #1057.

### CODE REVIEW

**Comment by ctb** [comment]
- [ ] Is it mergeable?
- [ ] Did it pass the tests?
- [ ] If it introduces new functionality in scripts/ is it tested?
  Check for code coverage with `make clean diff-cover`
- [ ] Is it well formatted? Look at `make pep8`, `make diff_pylint_report`,
  `make cppcheck`, and `make doc` output. Use `make format` and manual
  fixing as needed.
- [ ] Did it change the command-line interface? Only additions are allowed
  without a major version increment. Changing file formats also requires a
  major version number increment.
- [ ] Is it documented in the ChangeLog?
  http://en.wikipedia.org/wiki/Changelog#Format
- [ ] Was a spellchecker run on the source code and documentation after
  changes were made?
- [ ] Is the Copyright year up to date?

**Comment by ctb** [comment]
Ready for review & merge @luizirber @camillescott @bocajnotnef

**Comment by ctb** [comment]
Specifically, note no change (decrease) in test coverage of normalize-by-median.

**Comment by bocajnotnef** [comment]
I didn't realize we were changing `DEFAULT_DESIRED_COVERAGE`. Also, the move of all the tests into their own file makes sense (there are a *lot* of tests) but seems counter-intuitive.

That's above my paygrade though. LGTM.

**Comment by ctb** [comment]
@bocajnotnef the change to DEFAULT_DESIRED_COVERAGE is up for discussion in #1073 if you have questions or concerns.  I'm not sure why putting the tests in their own file is counter-intuitive to you but happy to discuss it.

**Comment by bocajnotnef** [comment]
I just figure if we have a `test_scripts.py` all the tests for the scripts should go in there, yeah? Or each script should have its individual test file (but then we'd have twelve new test files). I just think it's strange to do only normalize_by_median and not any others (the partition_graph tests and everything that relies on the `_make_graph` function come to mind)

**Comment by ctb** [comment]
On Sat, Jun 13, 2015 at 11:59:03AM -0700, Jake Fenton wrote:
> I just figure if we have a `test_scripts.py` all the tests for the scripts should go in there, yeah? Or each script should have its individual test file (but then we'd have twelve new test files). I just think it's strange to do only normalize_by_median and not any others (the partition_graph tests and everything that relies on the `_make_graph` function come to mind)

Rationale:

One step at a time. If you end up working in that area of the code and
felt like breaking it out, then go ahead.  -0 on changes that are solely
reorganizational, though; there's a nearly infinite number of them to
do, and it just ends up in code churn.

**Comment by bocajnotnef** [comment]
Alright, makes sense.

**Comment by mr-c** [comment]
LGTM, futurizing to py3+py2

**Comment by mr-c** [comment]
+ rebasing

**Comment by mr-c** [comment]
Jenkins, test this please

**Pull request merged**
