### PR TITLE
Update CPP examples to new oxli/cython setup

### PR DESCRIPTION
**Pull request by betatim**
This doesn't contain the modification to `setup.py` that I needed to make it work locally. Need to decide why/if it is needed or not.

- [x] Is it mergeable?
- [x] `make test` Did it pass the tests?

### CODE REVIEW

**Comment by betatim** [comment]
Paging @camillescott and @standage for cython wisdom and merge.

**Comment by betatim** [comment]
This PR is against #1595

**Comment by standage** [comment]
Compiles and runs on my machine :)

**Comment by betatim** [comment]
Merge?

**Comment by standage** [comment]
However, I don't understand why it took 45+ seconds of hard thinking to execute `make help` on this branch, which shouldn't be touching `setup.py` or anything else in the dev environment AFAICT.

**Comment by standage** [comment]
I'll defer to @camillescott on merging.

**Comment by betatim** [comment]
Not sure about `make help`. My guess would be one of the variables that uses `shell` is to blame?

**Comment by betatim** [comment]
Is the `make help` thing also a problem on the original cython branch?

It would be good if we can keep rolling to get this cython thing done and dusted, so shall we merge this instead of waiting for Camille?

**Comment by camillescott** [comment]
Welp sorry to say that I fixed this already on the plane to Hawaii last week, but forgot to push the commit. So, closing this pull. Sorry @betatim

**Comment by betatim** [comment]
Tzz

**Pull request closed without merging**
