### PR TITLE
Refactor diginorm reporting

### PR DESCRIPTION
**Pull request by ctb**
This PR further refactors the diginorm script after #1010 and #1057.

Briefly,

* shifts tracking of sequences read/kept into the WithDiagnostics wrapper, which makes it much
   more general (so e.g. I think we can reuse this code in trim-low-abund.py);
* allows for users setting the reporting frequency via the command line;
* exchanges the expensive modulus operator for a simple comparison watermark approach;
* the watermark approach allows for increments of more than one sequence, which allows for more correct reporting during broken-paired reading;
* adds lightweight tests for report_fp that can be run frequently;

### CODE REVIEW

**Comment by ctb** [comment]
- [ ] Is it mergeable?
- [ ] Did it pass the tests?
- [ ] If it introduces new functionality in scripts/ is it tested?
  Check for code coverage with `make clean diff-cover`
- [ ] Is it well formatted? Look at `make pep8`, `make diff_pylint_report`,
  `make cppcheck`, and `make doc` output. Use `make format` and manual
  fixing as needed.
- [ ] Did it change the command-line interface? Only additions are allowed
  without a major version increment. Changing file formats also requires a
  major version number increment.
- [ ] Is it documented in the ChangeLog?
  http://en.wikipedia.org/wiki/Changelog#Format
- [ ] Was a spellchecker run on the source code and documentation after
  changes were made?
- [ ] Is the Copyright year up to date?

**Comment by ctb** [comment]
Running code coverage analysis now; in the meantime, @bocajnotnef, any comments?

@luizirber any thoughts you have on making use of coroutine functionality in WithDiagnostics would be most welcome.

**Comment by ctb** [comment]
Code coverage is 100%. Ready for review @mr-c @camillescott @bocajnotnef.

**Comment by bocajnotnef** [comment]
LGTM! I dig.

**Comment by camillescott** [comment]
Does this mean the decorator idea is a no-go?

**Comment by ctb** [comment]
Explain?

--
Titus Brown, ctbrown@ucdavis.edu

**Comment by camillescott** [comment]
regarding https://github.com/dib-lab/khmer/pull/1057#issuecomment-109082444

**Comment by ctb** [comment]
On Mon, Jul 20, 2015 at 10:49:54AM -0700, Camille Scott wrote:
> regarding https://github.com/dib-lab/khmer/pull/1057#issuecomment-109082444

OK, thought I remembered something about that.  No objections & that's
where I want to head, but I think this is a nice refactor along the way
to that.

**Comment by ctb** [comment]
If there's no objection to merging, could someone please merge? :)

**Comment by camillescott** [comment]
Makes sense! Looks good to me; tests pass on clean environment. Merging.

**Comment by ctb** [comment]
w00t thx!

**Pull request merged**
