### PR TITLE
Put copy_test_data in all but a few test functions as Issue #1405

### PR DESCRIPTION
**Pull request by rcs333**
- [x] Is it mergeable?
- [x] `make test` Did it pass the tests?
- [x] `make clean diff-cover` If it introduces new functionality in
  `scripts/` is it tested?
- [x] `make format diff_pylint_report cppcheck doc pydocstyle` Is it well
  formatted?
- [x] Did it change the command-line interface? Only additions are allowed
  without a major version increment. Changing file formats also requires a
  major version number increment.
- [x] Is it documented in the `ChangeLog`?
  http://en.wikipedia.org/wiki/Changelog#Format
- [x] Was a spellchecker run on the source code and documentation after
  changes were made?
- [x] Do the changes respect streaming IO? (Are they
  tested for streaming IO?)
- [x] Is the Copyright year up to date?

I'm kind of new to this whole github thing so hopefully this is how I would go about contributing these very simple changes.

### CODE REVIEW

**Comment by standage** [comment]
Ok to test jenkins

**Comment by standage** [comment]
Don't be too concerns about the test results, our continuous integration setup has been a bit wonky recently.

**Comment by rcs333** [comment]
So do I need to do anything else to my code?

**Comment by standage** [comment]
Thanks for your contribution @rcs333, and sorry for the confusion @rcs333! We have a continuous integration system set up to run tests whenever a pull request is submitted on GitHub. It's very nice--usually!--but right now our Mac OS X system isn't working correctly. I went ahead and ran the tests myself on Mac and an Ubuntu Linux machine, and your patch checks out!

[Our group's typical approach](https://khmer.readthedocs.io/en/v2.0/dev/for-khmer-developers.html) is to open a pull request soon after we begin working on an issue, and then once we're done we 1) go through the checklist to make sure we didn't miss anything and 2) when the checklist is complete, leave a comment saying "ready for review". At that point, we'll take a closer look and then provide feedback and/or merge.

So just let me know when you'd like to me do a thorough review. Thanks!

**Comment by standage** [comment]
retest this please jenkins

**Comment by standage** [comment]
I just did some troubleshooting on our OS X Jenkins server, so hopefully the automatic tests will run correctly this time!

**Comment by rcs333** [comment]
Ready for review! (I think!)

**Comment by standage** [comment]
After review, this looks good to me. And despite the lingering issues with the continuous integration server, I've verified that the tests pass on OS X. Merging now.

**Comment by standage** [comment]
Thanks for your contribution @rcs333!

**Pull request merged**
