### PR TITLE
Remove some mistakes from py3 branch

### PR DESCRIPTION
**Pull request by luizirber**
- setup.py was recompiling the module everytime (because zlib would be always compiled again)
- nose didn't stop on first error (setup.cfg)
- remove dependency on `future` (we were using it only for the queue/Queue stdlib module name change)

## Checklist

- [x] Is it mergeable?
- [x] Did it pass the tests?
- [x] If it introduces new functionality in scripts/ is it tested?
  Check for code coverage with `make clean diff-cover`
- [x] Is it well formatted? Look at `make pep8`, `make diff_pylint_report`,
  `make cppcheck`, and `make doc` output. Use `make format` and manual
  fixing as needed.
- [x] Did it change the command-line interface? Only additions are allowed
  without a major version increment. Changing file formats also requires a
  major version number increment.
- [x] Is it documented in the ChangeLog?
  http://en.wikipedia.org/wiki/Changelog#Format
- [x] Was a spellchecker run on the source code and documentation after
  changes were made?
- [x] Is the Copyright year up to date?

### CODE REVIEW

**Comment by luizirber** [comment]
ready for review and merge @mr-c

**Comment by mr-c** [comment]
LGTM but I added some more commits. @ctb @camillescott can you review & merge so we can un-break the build?

**Comment by mr-c** [comment]
For my rationale see the commit message for 9b173ec276e0393c6fe2fba24d9436ca22323839

**Comment by camillescott** [comment]
On the whole script/scriptpath thing: does this mean that only the installed versions of the scripts will be tested, as opposed to them being tested in-place?

**Comment by mr-c** [comment]
As you can see the current method is a no-op. Runscript takes care of
trying to find the script either in the local tree or elsewhere.

On Sat, Jun 13, 2015, 14:46 Camille Scott <notifications@github.com> wrote:

> On the whole script/scriptpath thing: does this mean that only the
> installed versions of the scripts will be tested, as opposed to them being
> tested in-place?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dib-lab/khmer/pull/1089#issuecomment-111754680>.
>
-- 
Michael R. Crusoe: Programmer & Bioinformatician crusoe@ucdavis.edu
<mcrusoe@msu.edu>
The lab for Data Intensive Biology; University of California, Davis
https://impactstory.org/MichaelRCrusoe http://twitter.com/biocrusoe

**Comment by camillescott** [comment]
Gotcha. I saw the no-op method, but had missed that runscript would take care of finding the script. LGTM; merging

**Pull request merged**
