### PR TITLE
s/ged/dib/g

### PR DESCRIPTION
**Pull request by mr-c**
& remove landscape.io

### CODE REVIEW

**Comment by standage** [comment]
Was there some offline discussion around landscape.io? Looks like a potentially useful tool, but perhaps not ready for primetime? As of PyCon, Python support was beta IIRC.

**Comment by mr-c** [comment]
No offline discussion, I yanked its GitHub permissions after it spammed our pull requests which broke the  badge.

**Comment by mr-c** [comment]
- [ ] Is it mergeable?
- [ ] Did it pass the tests?
- [ ] If it introduces new functionality in scripts/ is it tested?
  Check for code coverage with `make clean diff-cover`
- [ ] Is it well formatted? Look at `make pep8`, `make diff_pylint_report`,
  `make cppcheck`, and `make doc` output. Use `make format` and manual
  fixing as needed.
- [ ] Did it change the command-line interface? Only additions are allowed
  without a major version increment. Changing file formats also requires a
  major version number increment.
- [ ] Is it documented in the ChangeLog?
  http://en.wikipedia.org/wiki/Changelog#Format
- [ ] Was a spellchecker run on the source code and documentation after
  changes were made?
- [ ] Is the Copyright year up to date?

**Comment by mr-c** [comment]
@luizirber @camillescott @ctb ready for review & merge

**Comment by ctb** [comment]
Reviews welcome; please leave for me to merge :)

**Comment by luizirber** [comment]
:+1:

**Comment by ctb** [comment]
Sorry, thought this was a different PR - looks good to me, merging.

**Pull request merged**
