### PR TITLE
Fix streaming gzip output

### LINKED ISSUE #1363: `trim-low-abund.py ... --gzip -o -` fails on Python 3
Witness:

```
% scripts/trim-low-abund.py data/100k-filtered.fa --gzip -o - | gunzip -c > /dev/null
...
created temporary directory ./tmp_6iiq1ovkhmer; use -T to change location
Traceback (most recent call last):
  File "scripts/trim-low-abund.py", line 530, in <module>
    main()
  File "scripts/trim-low-abund.py", line 403, in main
    trimfp = get_file_writer(outfp, args.gzip, args.bzip)
  File "/Users/t/dev/khmer/khmer/kfile.py", line 236, in get_file_writer
    ofile = gzip.GzipFile(fileobj=file_handle, mode='w')
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/gzip.py", line 192, in __init__
    self._write_gzip_header()
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/gzip.py", line 220, in _write_gzip_header
    self.fileobj.write(b'\037\213')             # magic header
TypeError: write() argument must be str, not bytes
```

### PR DESCRIPTION
**Pull request by betatim**
Fixes #1363 

- [x] Is it mergeable?
- [x] `make test` Did it pass the tests?
- [x] `make clean diff-cover` If it introduces new functionality in
  `scripts/` is it tested?
- [x] `make format diff_pylint_report cppcheck doc pydocstyle` Is it well
  formatted?
- [x] Did it change the command-line interface? Only additions are allowed
  without a major version increment. Changing file formats also requires a
  major version number increment.
- [x] Is it documented in the `ChangeLog`?
  http://en.wikipedia.org/wiki/Changelog#Format
- [x] Was a spellchecker run on the source code and documentation after
  changes were made?
- [x] Do the changes respect streaming IO? (Are they
  tested for streaming IO?)
- [x] Is the Copyright year up to date?

### CODE REVIEW

**Comment by betatim** [comment]
(`<_io.StringIO object at 0x105497168>` (test) vs `<_io.TextIOWrapper name='<stdout>' mode='w' encoding='UTF-8'>` (shell))

**Comment by betatim** [comment]
There are some disagreements with `make format` about how to format python code and how much stuff I should add to the temporary hack class, but otherwise:

Ready for review! @luizirber, @camillescott, @standage , or @ctb

nb. at some point we should investigate how to modify the unit-tests that monkey about with std{in,out} so that we don't need to special case them in the code. Feels dirty.

**Comment by standage** [comment]
The OS X build on the last commit timed out. Just restarted.

**Comment by standage** [comment]
Actually, cancelling since we need to merge in master anyway.

**Comment by betatim** [comment]
🔄🎸 rebased.

(I think the OSX failure was the heisenbug from earlier related to thread safety (or lack thereof). Bumped into this in #1492, related #1248 )

**Comment by betatim** [comment]
Changed the imports to `from foo import FileType as khFileType` to make it more obvious that we are using our own `FileType` on purpose

**Pull request merged**
