### PR TITLE
Added get_temp_data function for tests utils

### PR DESCRIPTION
**Pull request by bocajnotnef**
see #1225

### CODE REVIEW

**Comment by bocajnotnef** [comment]
retest this, please

**Comment by bocajnotnef** [comment]
- [ ] Is it mergeable?
- [ ] Did it pass the tests?
- [ ] If it introduces new functionality in scripts/ is it tested?
  Check for code coverage with `make clean diff-cover`
- [ ] Is it well formatted? Look at `make pep8`, `make diff_pylint_report`,
  `make cppcheck`, and `make doc` output. Use `make format` and manual
  fixing as needed.
- [ ] Did it change the command-line interface? Only additions are allowed
  without a major version increment. Changing file formats also requires a
  major version number increment.
- [ ] Is it documented in the ChangeLog?
  http://en.wikipedia.org/wiki/Changelog#Format
- [ ] Was a spellchecker run on the source code and documentation after
  changes were made?
- [ ] Is the Copyright year up to date?

**Comment by bocajnotnef** [comment]
Ready for merge, @luizirber @camillescott

**Comment by mr-c** [comment]
LGTM. Lets use this everywhere

**Comment by bocajnotnef** [comment]
@mr-c Do you want me to go and put it wveerywhere it can be used/

**Comment by mr-c** [comment]
After the 2.0 release

**Comment by betatim** [comment]
The issues this refers to has been closed via #1400 -> closing this PR as well.

**Pull request closed without merging**
