### PR TITLE
initial null-o-mer script

### PR DESCRIPTION
**Pull request by ctb**
Requested by someone via e-mail; thought I'd add it to the examples.

Example output:
```
% python find-nullomers.py ~/dev/sourmash-tutorial/ecoliMG1655.fa.gz  | head
allocating lots of memory for exact counts: 4194304 bytes
consuming /Users/t/dev/sourmash-tutorial/ecoliMG1655.fa.gz
...done!
Iterating over all 11-mers
AAAAAAAAAAA 0
AAAAAAAAAAT 0
AAAAAAAAAAC 0
AAAAAAAAAAG 0
AAAAAAAAATA 3
AAAAAAAAATT 0
```

- [ ] Is it mergeable?
- [ ] `make test` Did it pass the tests?
- [ ] `make clean diff-cover` If it introduces new functionality in
  `scripts/` is it tested?
- [ ] `make format diff_pylint_report cppcheck doc pydocstyle` Is it well
  formatted?
- [ ] Did it change the command-line interface? Only backwards-compatible
  additions are allowed without a major version increment. Changing file
  formats also requires a major version number increment.
- [ ] For substantial changes or changes to the command-line interface, is it
  documented in `CHANGELOG.md`? See [keepachangelog](http://keepachangelog.com/)
  for more details.
- [ ] Was a spellchecker run on the source code and documentation after
  changes were made?
- [ ] Do the changes respect streaming IO? (Are they
  tested for streaming IO?)

### CODE REVIEW

**Comment by betatim** [comment]
Only question: what is a null-o-mer? Was guessing "all kmers with a count of zero" but then it prints all of them.

Otherwise LGTM.

**Comment by ctb** [comment]
yes, what you thought. I'm asking the requestor what exact output they want.

**Review by betatim — APPROVED** [review]
Merge when ready @ctb

**Comment by ctb** [comment]
I am saddened by the failure of several different reviewers to test this code... tsk tsk.

**Comment by ctb** [comment]
And the merge of a PR with none of the checkboxes ticked also seems problematic. tsk tsk.

**Comment by luizirber** [comment]
http://youshallnotpass.review

**Pull request merged**
