### PR TITLE
[MRG] Test python 3.4 support

### LINKED ISSUE #1772: Duplicated metadata in setup.py
Didn't want to hold up the recent PR, but the supported Python versions listed in the current `setup.py` has 3.5 duplicated. See https://github.com/dib-lab/khmer/pull/1755#pullrequestreview-61073008.

### PR DESCRIPTION
**Pull request by standage**
There doesn't appear to be any reason khmer can't support Python 3.4. I propose we should support it and explicitly test it until we have a compelling reason not to.

Closes #1772.

- [x] Is it mergeable?
- [x] `make test` Did it pass the tests?
- [x] `make clean diff-cover` If it introduces new functionality in
  `scripts/` is it tested?
- [x] `make format diff_pylint_report cppcheck doc pydocstyle` Is it well
  formatted?
- [x] Did it change the command-line interface? Only backwards-compatible
  additions are allowed without a major version increment. Changing file
  formats also requires a major version number increment.
- [x] For substantial changes or changes to the command-line interface, is it
  documented in `CHANGELOG.md`? See [keepachangelog](http://keepachangelog.com/)
  for more details.
- [x] Was a spellchecker run on the source code and documentation after
  changes were made?
- [x] Do the changes respect streaming IO? (Are they
  tested for streaming IO?)

### CODE REVIEW

**Comment by standage** [comment]
Ready for review and merge! @ctb @luizirber @camillescott

**Comment by standage** [comment]
> should we test the earliest (3.4) and latest (3.6) versions of python?

Easy enough. I've added support, although we may want to clean up the travis config if possible.

**Comment by betatim** [comment]
Nods, duplication everywhere. I was thinking just 3.4 and 3.6, skipping 3.5.

**Comment by betatim** [comment]
Merging for now, we can remove it later.

**Pull request merged**
