### PR TITLE
The style roller

### PR DESCRIPTION
**Pull request by betatim**
After running `make format` for another PR I ended up with a clobbered `setup.py` and various other/unrelated files got modified. This is a PR that does nothing but execute those commands.

I also removed `setup.py` from the CPPSOURCES variable in `Makefile` otherwise `astyle` does its thing on it which leads to 😕.

Should jenkins be running `make format` and giving an error if it changes a file? Personally I prefer `pep8` as a guideline instead of hard rules, but then it is in the checklist for this project.

---

- [x] Is it mergeable?
- [x] `make test` Did it pass the tests?
- [x] `make clean diff-cover` If it introduces new functionality in
  `scripts/` is it tested?
- [x] `make format diff_pylint_report cppcheck doc pydocstyle` Is it well
  formatted?
- [x] Is it documented in the `ChangeLog`?
  http://en.wikipedia.org/wiki/Changelog#Format
- [x] Was a spellchecker run on the source code and documentation after
  changes were made?
- [x] Is the Copyright year up to date?

### CODE REVIEW

**Comment by betatim** [comment]
Looking at what `astyle` does, I would disagree with some of those changes. Am I using a weird version `Artistic Style Version 2.05.1`?

**Comment by betatim** [comment]
Test this please jenkins

**Comment by betatim** [comment]
Any ideas why the coverage drops so much after reformatting? I am officially out of ideas 😢

**Comment by standage** [comment]
@betatim Sorry, no ideas. I've never seen coverage drop that much for any PR. Especially odd that it should be a strictly formatting PR...

**Comment by mr-c** [comment]
`setup.py` was included in the CPP sources list as options there affect compilation. So if you want to remove from that list you'll need to add it back in on every compilation related target, or choose another approach like filtering out `setup.py` from the list during the format call.

**Comment by betatim** [comment]
Test this please jenkins

**Comment by betatim** [comment]
Test this please jenkins

**Comment by betatim** [comment]
Retest this please jenkins

**Comment by betatim** [comment]
Ready for review! @luizirber, @camillescott, @standage , or @ctb

This is (essentially) the result of running `make format pydocstyle` and doing what it tells you to do plus its automatic changes.

**Comment by standage** [comment]
LGTM. Once you resolve the conflict I can merge.

**Comment by betatim** [comment]
👌

**Pull request merged**
