### PR TITLE
[WIP] use NonLoopingAT in LinearAssembler to avoid backtracking

### PR DESCRIPTION
**Pull request by ctb**
I think we need a test, and that's about it.

- [ ] Is it mergeable?
- [ ] `make test` Did it pass the tests?
- [ ] `make clean diff-cover` If it introduces new functionality in
  `scripts/` is it tested?
- [ ] `make format diff_pylint_report cppcheck doc pydocstyle` Is it well
  formatted?
- [ ] Did it change the command-line interface? Only backwards-compatible
  additions are allowed without a major version increment. Changing file
  formats also requires a major version number increment.
- [ ] For substantial changes or changes to the command-line interface, is it
  documented in `CHANGELOG.md`? See [keepachangelog](http://keepachangelog.com/)
  for more details.
- [ ] Was a spellchecker run on the source code and documentation after
  changes were made?
- [ ] Do the changes respect streaming IO? (Are they
  tested for streaming IO?)

### CODE REVIEW

**Comment by ctb** [comment]
@camillescott says this is in her latest cython & assembler foo already.

**Comment by betatim** [comment]
Add a test to this and then merge o should we cherry pick something from @camillescott ?

**Comment by standage** [comment]
Unless @ctb has a test conceived for this already, I can dig up a test case pretty quickly. This came up between @camillescott and I recently, and I'm pretty sure I posted an offending data file in the issue tracker.

**Comment by ctb** [comment]
I do not!

**Comment by camillescott** [comment]
I think it might be best to cherry pick a fix for it from my branch. Willing to do that now.

**Comment by ctb** [comment]
Seems more complicated than applying a 6 line patch, no?

**Comment by camillescott** [comment]
Also, doesn't use the same seen set for bidirected assembly.

**Comment by ctb** [comment]
that seems like the relevant comment, yes ;)

**Comment by standage** [comment]
Closing in favor of #1701.

**Pull request closed without merging**
