### PR TITLE
Documentation for standard/reserved command-line options

### LINKED ISSUE #1211: Document reserved/standard command line options in dev docs
I'm thinking -x, -N, -M, -U, -k, and maybe -q deserve to always mean the same thing on any script.

### PR DESCRIPTION
**Pull request by standage**
Fixes #1211.

- [x] Is it mergeable?
- [x] `make test` Did it pass the tests?
<strike>- [ ] `make clean diff-cover` If it introduces new functionality in
  `scripts/` is it tested?</strike>
- [x] `make format diff_pylint_report cppcheck doc pydocstyle` Is it well
  formatted?
<strike>- [ ] Did it change the command-line interface? Only additions are allowed
  without a major version increment. Changing file formats also requires a
  major version number increment.</strike>
- [x] Is it documented in the `ChangeLog`?
  http://en.wikipedia.org/wiki/Changelog#Format
- [x] Was a spellchecker run on the source code and documentation after
  changes were made?
<strike>- [ ] Do the changes respect streaming IO? (Are they
  tested for streaming IO?)</strike>
- [x] Is the Copyright year up to date?

### CODE REVIEW

**Comment by standage** [comment]
Ready for review @ctb @betatim @luizirber @camillescott.

**Comment by ctb** [comment]
LGTM. But needs the rest of the checkboxes :)

**Comment by standage** [comment]
Indeed. In the mean time, I'm working on the change log and copyright date issues...

**Comment by standage** [comment]
Done

**Comment by standage** [comment]
Ok, build passed and ready for merge.

**Comment by standage** [comment]
I know the tests include some API enforcement, but I can't find it at the moment. I would've expected it to be in `test_scripts.py` or `test_script_arguments.py`, but I didn't find it with a quick scan.

**Comment by ctb** [comment]
I don't think we have anything formal.  There is something where we check
that citation information is properly displayed.

**Comment by standage** [comment]
That must've been what I was thinking. That would be a good template for automated enforcement of required flags.

**Comment by ctb** [comment]
-0 unless we can encode it in a for loop that applies to all scripts/ 
(see for example the test_sandbox_scripts loop), in which case +1 :).  We don't
add scripts that often; making it harder to add scripts is a bad thing; putting
lots of effort into automating the testing of command line APIs is probably not
useful.

**Pull request merged**
