### PR TITLE
Supply PR template

### PR DESCRIPTION
**Pull request by standage**
Awesome [new feature](https://github.com/blog/2111-issue-and-pull-request-templates) from GitHub today. Something we want to use?

### CODE REVIEW

**Comment by luizirber** [comment]
That's great! But I think we can put the templates inside the `.github` dir, to avoid cluttering the (already cluttered) root directory.

**Comment by standage** [comment]
Good idea.

**Comment by standage** [comment]
Guess I'd better, uh, post the checklist.

**Comment by standage** [comment]
- [ ] Is it mergeable?
- [ ] Did it pass the tests?
- [ ] If it introduces new functionality in scripts/ is it tested?
  Check for code coverage with `make clean diff-cover`
- [ ] Is it well formatted? Look at `make pep8`, `make diff_pylint_report`,
  `make cppcheck`, and `make doc` output. Use `make format` and manual
  fixing as needed.
- [ ] Did it change the command-line interface? Only additions are allowed
  without a major version increment. Changing file formats also requires a
  major version number increment.
- [ ] Is it documented in the ChangeLog?
  http://en.wikipedia.org/wiki/Changelog#Format
- [ ] Was a spellchecker run on the source code and documentation after
  changes were made?
- [ ] Do the changes respect streaming IO? (Are they
  tested for streaming IO?)
- [ ] Is the Copyright year up to date?

**Comment by standage** [comment]
Would I want to update both the MSU and UC dates at the top of the file, or just the UC date?

**Comment by luizirber** [comment]
@standage just UC

**Comment by standage** [comment]
Ok, done and ready for review.

**Comment by luizirber** [comment]
LGTM, thanks @standage!

**Pull request merged**
