### PR TITLE
try a class for the core processing bit of normalize-by-median

### PR DESCRIPTION
**Pull request by ctb**
So @bocajnotnef here you could replace normalize_by_median_and_check with several functions in Normalizer, build a new Normalizer for each input file, and then accumulate total/discarded in the outermost for loop across all the filenames.  Make some sense?

The basic idea is to replace globals with objects that "package" all of that information in one place.

### CODE REVIEW

**Comment by bocajnotnef** [comment]
Right, okay. I can run with this. Thanks!

**Comment by ctb** [comment]
On Thu, May 28, 2015 at 08:01:53AM -0700, Jake Fenton wrote:
> Right, okay. I can run with this. Thanks!

p.s. it even passes most of the tests! :)

**Comment by bocajnotnef** [comment]
retest this please

**Comment by luizirber** [comment]
This class is almost a context manager itself, if you rename `__call__` to `__iter__` and implement `__enter__` and `__exit__` for initialization

**Comment by ctb** [comment]
On Fri, May 29, 2015 at 08:59:33AM -0700, Luiz Irber wrote:
> This class is almost a context manager itself, if you rename `__call__` to `__iter__` and implement `__enter__` and `__exit__` for initialization

thanks - that was my suspicion but I decided to leave it for someone else
to confirm :)

**Pull request merged**
