### PR TITLE
Update fastq-to-fasta.py

### PR DESCRIPTION
**Pull request by ACharbonneau**
Changed '-n' default description to match behaviour

### CODE REVIEW

**Comment by mr-c** [comment]
Jenkins, add to testlist

**Comment by mr-c** [comment]
Thanks, @ACharbonneau ! Can you paste the checklist from http://khmer.readthedocs.org/en/latest/dev/coding-guidelines-and-review.html#checklist ?

**Comment by ctb** [comment]
ping @ACharbonneau

**Comment by ACharbonneau** [comment]
- [ ] Is it mergeable?
- [ ] Did it pass the tests?
- [ ] If it introduces new functionality in scripts/ is it tested?
  Check for code coverage with `make clean diff-cover`
- [ ] Is it well formatted? Look at `make pep8`, `make diff_pylint_report`,
  `make cppcheck`, and `make doc` output. Use `make format` and manual
  fixing as needed.
- [ ] Did it change the command-line interface? Only additions are allowed
  without a major version increment. Changing file formats also requires a
  major version number increment.
- [ ] Is it documented in the ChangeLog?
  http://en.wikipedia.org/wiki/Changelog#Format
- [ ] Was a spellchecker run on the source code and documentation after
  changes were made?
- [ ] Is the Copyright year up to date?

**Comment by bocajnotnef** [comment]
ping @ACharbonneau

**Comment by ACharbonneau** [comment]
Hey,

So this was only a change to the comments & help, so the description matches what the script actually does; which presumably means it will pass all the tests. However, I cannot get tests to run correctly on my machine. See: https://github.com/dib-lab/khmer/issues/1156#issuecomment-123918502

If you guys don't want to merge it in without tests, I can close the pull request and let someone else fix it, or I'll finish the tests as soon as we get my computer to run them. Sorry :(

**Comment by mr-c** [comment]
Let's keep this open; @bocajnotnef will polish it for you. Thank you for
your contribution!

On Wed, Jul 29, 2015, 08:28 Amanda Charbonneau <notifications@github.com>
wrote:

> Hey,
>
> So this was only a change to the comments & help, so the description
> matches what the script actually does; which presumably means it will pass
> all the tests. However, I cannot get tests to run correctly on my machine.
> See: #1156 (comment)
> <https://github.com/dib-lab/khmer/issues/1156#issuecomment-123918502>
>
> If you guys don't want to merge it in without tests, I can close the pull
> request and let someone else fix it, or I'll finish the tests as soon as we
> get my computer to run them. Sorry :(
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dib-lab/khmer/pull/814#issuecomment-125988865>.
>
-- 
Michael R. Crusoe: Programmer & Bioinformatician crusoe@ucdavis.edu
The lab for Data Intensive Biology; University of California, Davis
https://impactstory.org/MichaelRCrusoe http://twitter.com/biocrusoe

**Comment by bocajnotnef** [comment]
"Merged" #814--Thanks @ACharbonneau!

**Pull request merged**
