### PR TITLE
[MRG] Introduce consume_seqfile_banding method, part duex

### LINKED ISSUE #1570: Implement a new 'consume' method that only stores a fraction of the observed k-mers
I'm proposing a new method for the (count|node)(table|graph) classes that will deterministically consume only a fraction of the k-mers observed in the reads processed. The basic idea is to use some property of the k-mer's hashed value to split it into multiple (roughly equally sized) bins, so that those bins can be analyzed independently with much lower memory requirements. The simplest approach would be to just split up the hashed values using a modulus, but this is expensive to compute. An alternative approach would be to split on the first few or last few nucleotides (which depending on the hash function used might require discarding k-mers before hashes are computed), but some prefixes/suffixes are much more abundant than others (for example, A-rich sequences in human). It would probably be best to split into 2^n bins by looking at the value encoded in the n least significant bits of the hashed k-mer.

I would suggest a Python interface like this.

```python
cg = khmer.Countgraph(31, 1e9, 4)
# consume only k-mers with 0011 as their last 4 bits
cg.consume_fasta_bitsplit('reads.fq', 16, 3)
```

### PR DESCRIPTION
**Pull request by standage**
In #1571, I introduced bulk loading method with k-mer banding. Two issues though: 1) It only supported using 2^N bands; 2) The PR was against the pre-Cython codebase. I figured it would be easier to start over than merge master and fix.

This new PR splits the `uint64_t` hash space into N intervals and checks whether the hashed k-mer is in the specified interval.

Closes #1570.

- [x] Is it mergeable?
- [x] `make test` Did it pass the tests?
- [x] `make clean diff-cover` If it introduces new functionality in
  `scripts/` is it tested?
- [x] `make format diff_pylint_report cppcheck doc pydocstyle` Is it well
  formatted?
- [x] Did it change the command-line interface? Only backwards-compatible
  additions are allowed without a major version increment. Changing file
  formats also requires a major version number increment.
- [x] For substantial changes or changes to the command-line interface, is it
  documented in `CHANGELOG.md`? See [keepachangelog](http://keepachangelog.com/)
  for more details.
- [x] Was a spellchecker run on the source code and documentation after
  changes were made?
- [x] Do the changes respect streaming IO? (Are they
  tested for streaming IO?)

### CODE REVIEW

**Comment by standage** [comment]
I considered adding these functions to the `MurmurHashtable` class instead of the `Hashtable` class, since the banding isn't very effective with the 2-bit encoding. I decided not to for two reasons. First, using banding on \*graph data structures won't lead to any issues with **correctness**, it just won't have the same performance improvements that the \*table data structures get. Second, the CPython code doesn't have any scaffolding for the MurmurHashtable class, and I am loathe to slog through that.

**Comment by standage** [comment]
That said, ready for review and merge! @camillescott @luizirber @betatim @ctb

**Review by ctb — APPROVED** [review]
Looks good to me! Some tests on num bands that aren't powers of two might be good if you're feeling suspicious, though?

**Comment by standage** [comment]
> Some tests on num bands that aren't powers of two might be good if you're feeling suspicious, though?

Done. Will merge when the build completes.

**Pull request merged**
