### PR TITLE
Clean up print statement in check_space

### PR DESCRIPTION
**Pull request by souravsingh**
- [x] Is it mergeable?
- [x] `make test` Did it pass the tests?
- [ ] `make clean diff-cover` If it introduces new functionality in
  `scripts/` is it tested?
- [x] `make format diff_pylint_report cppcheck doc pydocstyle` Is it well
  formatted?
- [ ] Did it change the command-line interface? Only backwards-compatible
  additions are allowed without a major version increment. Changing file
  formats also requires a major version number increment.
- [ ] For substantial changes or changes to the command-line interface, is it
  documented in `CHANGELOG.md`? See [keepachangelog](http://keepachangelog.com/)
  for more details.
- [x] Was a spellchecker run on the source code and documentation after
  changes were made?
- [x] Do the changes respect streaming IO? (Are they
  tested for streaming IO?)

### CODE REVIEW

**Comment by souravsingh** [comment]
xref #1585

**Comment by standage** [comment]
Thanks @souravsingh. The TravisCI errors are unrelated to your changes. I'll see what we can do on this.

**Comment by souravsingh** [comment]
The tests are still failing. Is there any fix for it?

**Comment by standage** [comment]
I just restarted the build. Let's see if that fixes it.

**Comment by souravsingh** [comment]
The tests are failing. Let me try and make a new PR

**Comment by betatim** [comment]
The new PR for this is #1813

**Pull request closed without merging**
