### PR TITLE
Fix the skipping of sandbox script tests

### PR DESCRIPTION
**Pull request by betatim**
scripts in the sandbox will only be tested if the tests are executed
from within the source code repository. Use `skipif` to skip a test instead
of having an exception being raised that then confuses `runscript()`.

Related to #1646 

- [x] Is it mergeable?
- [x] `make test` Did it pass the tests?
- [x] `make clean diff-cover` If it introduces new functionality in
  `scripts/` is it tested?
- [x] `make format diff_pylint_report cppcheck doc pydocstyle` Is it well
  formatted?
- [x] Was a spellchecker run on the source code and documentation after
  changes were made?

### CODE REVIEW

**Comment by betatim** [comment]
In a new env:
```
$ pip install git+https://github.com/dib-lab/khmer@fix/sandbox-script-testing
$ pytest -s --pyargs khmer.tests.test_sandbox_scripts::test_sweep_reads
```
now succeeds. As in skips the test.

**Comment by betatim** [comment]
@standage could you try out those two lines to see if this also makes it work for you? Not sure I have a good idea why it would work on linux but not OSX.

**Comment by betatim** [comment]
Related question, should we add to travis a step of "install this as a module and re-run the tests" to check this doesn't break again in the future?

**Comment by ctb** [comment]
note, it's part of the release checklist

**Comment by betatim** [comment]
Exactly, trying to think of a reason why we shouldn't automate it. One less thing that comes as an unpleasant surprise when going through the checklist.

**Comment by ctb** [comment]
it would add a reasonable amount of compute time, no? I guess I'm -0 on it
for that reason alone, but that's a weak -0.

**Comment by betatim** [comment]
Probably would add ~3min to something that takes 11min to run (plus the wait for a OSX instance which rules us all).

---

Ready for review! @luizirber, @camillescott, @standage , or @ctb In particular if someone can confirm that the two steps above work locally on OSX.

**Pull request merged**
