### PR TITLE
CQF is replaced by MQF

### PR DESCRIPTION
**Pull request by shokrof**
MQF, Mixed Quotient Filter, is a new variant of [CQF](https://github.com/splatlab/cqf). MQF has changed the counting eschme of the parent data structure by adding fixed size counters and using different encoding for the dynamic one.
This improvement makes MQF more memory efficient for a wider range of zipfian distributions. Also, MQF expanded the metadata component of the filter to enable tagging of its kmers. In addition to the basic functions provided by the original CQF, the new datastructure comes with an expanding list of kmer processing functions including functions for merging and resizing the filter, functions for comparing kmer sets, and functions for indexing and meta-analysis of  multiple kmer groups. More details about these functions can be found [here](https://github.com/dib-lab/khmer/tree/MQFIntegration/third-party/mqf)   
- [x] Is it mergeable?
- [x] `make test` Did it pass the tests?
- [x] `make clean diff-cover` If it introduces new functionality in
  `scripts/` is it tested? No new functionality is added
- [ ] `make format diff_pylint_report cppcheck doc pydocstyle` Is it well
  formatted? 
      **Khmer source files are changed after running this command.**
- [x] Did it change the command-line interface? Only backwards-compatible
  additions are allowed without a major version increment. Changing file
  formats also requires a major version number increment. 
- [x] For substantial changes or changes to the command-line interface, is it
  documented in `CHANGELOG.md`? See [keepachangelog](http://keepachangelog.com/)
  for more details.
- [x] Was a spellchecker run on the source code and documentation after
  changes were made?
- [x] Do the changes respect streaming IO? (Are they
  tested for streaming IO?)

### CODE REVIEW

**Comment by shokrof** [comment]
@standage  can you help me with this error?
travis build succeeds on Linux but it fails on OSX. 
Build link: https://travis-ci.org/dib-lab/khmer/jobs/373855996.
Error: /Users/travis/.travis/job_stages: line 166: shell_session_update: command not found

**Comment by ctb** [comment]
not sure what's causing it but here's the only problem I can find:

Undefined symbols for architecture x86_64:
  "std::ostream::seekp(std::fpos<__mbstate_t>)", referenced from:
      _qf_init in gqf.o
  "std::ostream::operator<<(int)", referenced from:
      _qf_init in gqf.o
  "std::string::_Rep::_M_destroy(std::allocator<char> const&)", referenced from:
      _qf_remove in gqf.o
      _qf_init in gqf.o
      _qf_remove_tag in gqf.o
      _qf_get_tag in gqf.o
      insert(quotient_filter*, unsigned __int128, unsigned long long, bool, bool) in gqf.o
      _qf_iterator in gqf.o
      _qfi_get in gqf.o
      ...
  "std::string::_Rep::_S_empty_rep_storage", referenced from:
      _qf_remove in gqf.o
      _qf_init in gqf.o
      _qf_remove_tag in gqf.o
      _qf_get_tag in gqf.o
      insert(quotient_filter*, unsigned __int128, unsigned long long, bool, bool) in gqf.o
      _qf_iterator in gqf.o
      _qfi_get in gqf.o
      ...
  "std::basic_string<char, std::char_traits<char>, std::allocator<char> >::basic_string(char const*, std::allocator<char> const&)", referenced from:
      _qf_remove in gqf.o
      _qf_init in gqf.o
      _qf_remove_tag in gqf.o
      _qf_get_tag in gqf.o
      insert(quotient_filter*, unsigned __int128, unsigned long long, bool, bool) in gqf.o
      _qf_iterator in gqf.o
      _qfi_get in gqf.o
      ...
  "std::logic_error::logic_error(std::string const&)", referenced from:
      _qf_merge in gqf.o
      _qf_equals in gqf.o
      _qf_intersect in gqf.o
      _qf_subtract in gqf.o
      _qf_multi_merge in gqf.o
      _qf_resize in gqf.o
  "std::__basic_file<char>::~__basic_file()", referenced from:
      _qf_init in gqf.o
  "std::domain_error::domain_error(std::string const&)", referenced from:
      _qf_init in gqf.o
  "std::out_of_range::out_of_range(std::string const&)", referenced from:
      _qf_remove in gqf.o
      _qf_remove_tag in gqf.o
      _qf_get_tag in gqf.o
      insert(quotient_filter*, unsigned __int128, unsigned long long, bool, bool) in gqf.o
      _qf_iterator in gqf.o
      _qfi_get in gqf.o
  "std::basic_filebuf<char, std::char_traits<char> >::close()", referenced from:
      _qf_init in gqf.o
  "std::basic_ofstream<char, std::char_traits<char> >::basic_ofstream(char const*, std::_Ios_Openmode)", referenced from:
      _qf_init in gqf.o
  "std::overflow_error::overflow_error(std::string const&)", referenced from:
      insert_replace_slots_and_shift_remainders_and_runends_and_offsets(quotient_filter*, int, unsigned long long, unsigned long long, unsigned long long const*, unsigned long long const*, unsigned long long, unsigned long long) in gqf.o
  "std::locale::~locale()", referenced from:
      _qf_init in gqf.o
  "std::ios_base::Init::Init()", referenced from:
      __GLOBAL__sub_I_gqf.c in gqf.o
  "std::ios_base::Init::~Init()", referenced from:
      __GLOBAL__sub_I_gqf.c in gqf.o
  "std::ios_base::~ios_base()", referenced from:
      _qf_init in gqf.o
  "std::basic_ios<char, std::char_traits<char> >::clear(std::_Ios_Iostate)", referenced from:
      _qf_init in gqf.o
  "VTT for std::basic_ofstream<char, std::char_traits<char> >", referenced from:
      _qf_init in gqf.o
  "vtable for std::basic_filebuf<char, std::char_traits<char> >", referenced from:
      _qf_init in gqf.o
  NOTE: a missing vtable usually means the first non-inline virtual member function has no definition.
  "vtable for std::basic_streambuf<char, std::char_traits<char> >", referenced from:
      _qf_init in gqf.o
  NOTE: a missing vtable usually means the first non-inline virtual member function has no definition.
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [liboxli.dylib.1] Error 1
make[1]: *** [../../src/oxli/liboxli.a] Error 2
make: *** [cpp-demos] Error 2
The command "make cpp-demos" exited with 2.

**Comment by ctb** [comment]
All the tests pass!!

To me, the changes to the current khmer code look straightforward (relatively speaking :). Any objections to merging? @luizirber @standage @camillescott ?

**Comment by shokrof** [comment]
@ctb 
The problem is not solved. The last commit was an experimental one.
I am using travis to test my code because I don't have Mac machine. It will be great If anybody with MAC machine can help me solving this problem.

**Comment by ctb** [comment]
What problems remain?

--
Titus Brown, ctbrown@ucdavis.edu

**Comment by shokrof** [comment]
The problem occurs when c compiler(I think clang) links the binaries together to create cpp-demo program. It seems that the compiler cant find the c++ standard library. 

Log : https://travis-ci.org/dib-lab/khmer/jobs/374119637

Linking Command:
c++  -O3 -fPIC -fno-omit-frame-pointer -Wall -Wstrict-null-sentinel -std=c++11 -I ../../include/ -I ../../third-party/seqan/core/include/ -I ../../third-party/smhasher/ -I ../../third-party/mqf/ -I ../../third-party/rollinghash  -I ../../third-party/zlib/ -I ../../third-party/bzip2/  -DSEQAN_HAS_ZLIB=1 -DSEQAN_HAS_BZIP2=1 -O3 -fPIC -fno-omit-frame-pointer -Wall -DVERSION= -DNO_UNIQUE_RC=0  -lstdc++ -pthread -install_name /usr/local/lib/liboxli.dylib.1 -compatibility_version 1 -current_version 1 -shared -o liboxli.dylib.1 hashtable.o hashgraph.o hllcounter.o kmer_hash.o labelhash.o traversal.o read_aligner.o read_parsers.o subset.o kmer_filters.o assembler.o alphabets.o murmur3.o storage.o ../../third-party/zlib/adler32.lo ../../third-party/zlib/crc32.lo ../../third-party/zlib/deflate.lo ../../third-party/zlib/infback.lo ../../third-party/zlib/inffast.lo ../../third-party/zlib/inflate.lo ../../third-party/zlib/inftrees.lo ../../third-party/zlib/trees.lo ../../third-party/zlib/zutil.lo ../../third-party/zlib/compress.lo ../../third-party/zlib/uncompr.lo ../../third-party/zlib/gzclose.lo ../../third-party/zlib/gzlib.lo ../../third-party/zlib/gzread.lo ../../third-party/zlib/gzwrite.lo ../../third-party/bzip2/blocksort.o ../../third-party/bzip2/huffman.o ../../third-party/bzip2/crctable.o ../../third-party/bzip2/randtable.o ../../third-party/bzip2/compress.o ../../third-party/bzip2/decompress.o ../../third-party/bzip2/bzlib.o ../../third-party/mqf/gqf.o


Error:
Undefined symbols for architecture x86_64:
-  "std::ostream::seekp(std::fpos<__mbstate_t>)",
-  "std::string::_Rep::_M_destroy(std::allocator<char> const&)"
-  "std::string::_Rep::_S_empty_rep_storage"
and so on.

**Comment by standage** [comment]
I've recently seen weird behavior like this on my Mac as well. My solution was to set environmental variables `CC=gcc-7` and `CXX=g++-7`. This feels like a dirty hack and not a long term solution, but I couldn't find any other way to help Python compile and link C++ extensions correctly.

**Comment by shokrof** [comment]
@standage 
I tried to add these environmental variables in .travis.yml in this [commit](https://github.com/dib-lab/khmer/pull/1859/commits/068f6d498f64ce1005082a0f58feecb340b80938). it fails because it cant find g++-7.
Error: FileNotFoundError: [Errno 2] No such file or directory: 'gcc-7': 'gcc-7'
[Log](https://travis-ci.org/dib-lab/khmer/jobs/376036997).

I tried to set the variables to g++ and gcc. it fails to link the binaries.
[Log](https://travis-ci.org/dib-lab/khmer/jobs/376054911)

**Comment by ctb** [comment]
whups, `make cpp-demos` does not work on my laptop.

@shokrof could you open a new pull request to experiment, rather than experimenting on this branch? thx. then once we've figured stuff out we can update this branch once and for all.

**Comment by ctb** [comment]
The fix in https://github.com/dib-lab/khmer/pull/1865 works on my Mac laptop; let's see if it works via CI and on Linux!

**Comment by ctb** [comment]
Update from #1865 - still haven't solved the problem(s), but I am now guessing that the problem is that the MQF code is being compiled as a '.c' file despite the fact that it is using C++ commands inside. This may be interfering with linking the C++ code into as a CPython extension.

**Comment by ctb** [comment]
I spent a lot of time poking around on this yesterday. Digging around and comparing MQF with CQF, I have a few observations that may be causing the problem:

* the only difference between CQF and MQF code is that MQF code uses c++ code internally (see `std::` stuff)
* the compile time approaches and options between the two do not really vary at all
* so I thought the problem might lie in there somewhere. Perhaps the best plan would be to _either_ remove all the C++ code from MQF _or_ fully upgrade it to C++ rather than C.

I've been able to reproduce the problem on my laptop now, and I also note an interesting feature: I can run `make clean all cpp-demos`and generate the error; but then `cd third-party/mqf && make clean all; cd ../../; make cpp-demos`works!? There seems to be no variation in compile time arguments or anything for either mqf or cpp-demos between the first and second run, so it seems like an ordering problem of some sort.

Also, we don't use the shared library for linking the cpp-demos currently, so it's not clear to me why cpp-demos depends on sharedobj.

Anyway, that's it for now!

**Comment by shokrof** [comment]
I removed the linking command responsible for creating the shared library liboxli.dylib([log](https://travis-ci.org/dib-lab/khmer/jobs/381897145#L5323)).  Travis created the static library and used it to compile the cpp examples. However, It fails to run the examples because it can't find the stdlibc++. 

I searched how to include the stdlib in the static library but no luck. 
I found an interesting link maybe it is the reason. [Apple discourages the use of statically linked binaries on Macosx.](https://developer.apple.com/library/content/qa/qa1118/_index.html). It also may explain the weird behavior that you mentioned.

Should we start focus on creating the shared library and use it with the cpp demos?
It is also good to mention that MQF is successfully compiled and linked in khmer binaries. QFCounttable uses mqf instead of cqf, and [tests passed on Travis.](https://travis-ci.org/dib-lab/khmer/jobs/381897145#L4411)

**Comment by shokrof** [comment]
Bug is fixed in this pull request.
https://github.com/dib-lab/khmer/pull/1873

**Pull request closed without merging**
