### PR TITLE
Beyond 64bit hash values - alternate implementation

### PR DESCRIPTION
**Pull request by betatim**
Alternative way of storing hash values >64bit. Using a `bitset` should be as fast or faster than the `BigHashType` in #1455.

Converting between `PyLong` and a `bitset` is a bit cumbersome as we have to go via a string. Feedback on a better way of doing this welcome.

---

Any sane `bitset` implementation packs the bits into the largest integer available so it should be the same as the homebrew `BigHashType` for large number of bits. With free gains because the STL wizards do good things with vector instructions etc
- [ ] Is it mergeable?
- [ ] `make test` Did it pass the tests?
- [ ] `make clean diff-cover` If it introduces new functionality in
  `scripts/` is it tested?
- [ ] `make format diff_pylint_report cppcheck doc pydocstyle` Is it well
  formatted?
- [ ] Did it change the command-line interface? Only additions are allowed
  without a major version increment. Changing file formats also requires a
  major version number increment.
- [ ] Is it documented in the `ChangeLog`?
  http://en.wikipedia.org/wiki/Changelog#Format
- [ ] Was a spellchecker run on the source code and documentation after
  changes were made?
- [ ] Do the changes respect streaming IO? (Are they
  tested for streaming IO?)
- [ ] Is the Copyright year up to date?

### CODE REVIEW

**Comment by ctb** [comment]
On Tue, Oct 11, 2016 at 05:57:36AM -0700, Tim Head wrote:
> Alternative way of storing hash values >64bit. Using a `bitset` should be as fast or faster than the `BigHashType` in #1455.
> 
> Converting between `PyLong` and a `bitset` is a bit cumbersome as we have to go via a string. Feedback on a better way of doing this welcome.

I can't think of a good reason to make the number available in Python, note.
I think we just need an opaque object that we can stringify for debugging
if need be.

**Comment by betatim** [comment]
You don't want to have the result of `khmer.forward_hash` and similar available in python land?

**Comment by ctb** [comment]
On Tue, Oct 11, 2016 at 06:04:22AM -0700, Tim Head wrote:
> You don't want to have the result of `khmer.forward_hash` and similar available in python land?

I'm not sure we use it anywhere except for testing and debugging.

**Comment by betatim** [comment]
https://giphy.com/gifs/jonathan-pryce-narcopolis-8plTxLcdnBse4

**Comment by betatim** [comment]
On a more serious note: if it isn't used much I would stick with this approach of going via strings (and exclude that from the benchmark).

**Comment by ctb** [comment]
agree

**Pull request closed without merging**
