### PR TITLE
versioneer 0.15+dev

### LINKED ISSUE #1272: upgrade to latest versioneer release
Will quiet some warnings

- [x] review Jenkins build log and address all version related warnings

### PR DESCRIPTION
**Pull request by mr-c**
Includes fix for `git describe .. --match`

Fixes #1272 
Could address #1280 

Fixes issue with ReadTheDocs not willing to build the 'stable' release:
Before:
https://readthedocs.org/projects/khmer/builds/3307848/
After:
http://khmer.readthedocs.org/en/stable/

### CODE REVIEW

**Comment by mr-c** [comment]
- [ ] Is it mergeable?
- [ ] Did it pass the tests?
- [ ] If it introduces new functionality in scripts/ is it tested?
  Check for code coverage with `make clean diff-cover`
- [ ] Is it well formatted? Look at `make pep8`, `make diff_pylint_report`,
  `make cppcheck`, and `make doc` output. Use `make format` and manual
  fixing as needed.
- [ ] Did it change the command-line interface? Only additions are allowed
  without a major version increment. Changing file formats also requires a
  major version number increment.
- [ ] Is it documented in the ChangeLog?
  http://en.wikipedia.org/wiki/Changelog#Format
- [ ] Was a spellchecker run on the source code and documentation after
  changes were made?
- [ ] Do the changes respect streaming IO? (Are they
  tested for streaming IO?)
- [ ] Is the Copyright year up to date?

**Comment by mr-c** [comment]
PR description updated: https://github.com/dib-lab/khmer/pull/1299#issue-105440704
@luizirber @camillescott @ctb Ready for review & merge

**Comment by mr-c** [comment]
I've rebased; @luizirber @camillescott @ctb Ready for review & merge

**Comment by standage** [comment]
Merging (8 months *post facto* :)

**Pull request merged**
