### PR TITLE
Merge minor fixes to master into Cython branch

### PR DESCRIPTION
**Pull request by standage**
Just merged a couple of minor PRs into master in anticipation release. This PR brings Cython branch back into sync.

### CODE REVIEW

**Comment by standage** [comment]
This can be merged whenever convenient @camillescott.

**Comment by betatim** [comment]
(@camillescott is it Ok for you if we leave the PRs that merge stuff into the cython branch for you to approve/hit the big green button? I could help out but want to avoid stepping on each others toes.)

**Comment by standage** [comment]
Just merged #1235 into master as well as this PR.

**Comment by standage** [comment]
Already handled.

**Pull request closed without merging**
