### PR TITLE
[MRG] Document QFCounttable

### LINKED ISSUE #1748: Document QFCounttable constructor
The new `QFCounttable` constructor (thanks @betatim *et al.*!) is different from the constructor for [Count|Node][table|graph] objects, so we can't rely on similarity to intuit the `QFCounttable`'s behavior with respect to memory. The relationship between the arguments and memory usage for the Bloom filters is clear and documented: `bytes_used = num_buckets * num_tables / buckets_per_byte`.

What can we say about the memory usage of the `QFCounttable` based on the input parameters? Can we document this somewhere?

### PR DESCRIPTION
**Pull request by betatim**
Fixes #1748 related to #1751 

- [x] Is it mergeable?
- [x] `make test` Did it pass the tests?
- [x] `make clean diff-cover` If it introduces new functionality in
  `scripts/` is it tested?
- [x] `make format diff_pylint_report cppcheck doc pydocstyle` Is it well
  formatted?
- [ ] Was a spellchecker run on the source code and documentation after
  changes were made?

### CODE REVIEW

**Comment by betatim** [comment]
What do you think @standage ?

**Review by standage — APPROVED** [review]
This helps a lot. Should I merge?

**Comment by ctb** [comment]
+1 merge

**Comment by standage** [comment]
Ah, I just noticed the change from `[WIP]` to `[MRG]` in the title.

**Pull request merged**
