### PR TITLE
Disables pylint warnings for Jenkins. Fixes #326

### LINKED ISSUE #326: pylint complains too much about tests/
We should disable some of the pylint warnings just for the tests.

1686 warnings right now

Candidates:

C0103: Invalid constant name (789 warnings)
C0111: Missing module docstring (360 warnings)
E1101: missing member (319 warnings: due to pylint not being able to introspect the khmer module)
R0201: method could be a function  (23 warnings)
W0212: Access to a protected member of a client class (25 warnings)

### PR DESCRIPTION
**Pull request by moorepants**
I added a pylint config file with the disabled warnings and set the make target
to conditionally use the configuration file with pylint for the Jenkins build.

### CODE REVIEW

**Comment by mr-c** [comment]
@moorepants Interesting approach! We want to only disable those warnings for the `tests/` directory. I should have been more specific.

**Comment by moorepants** [comment]
Ok, I can update the pull request if you want. Are there any other details I need to know to move forward.

Also, how are the Jenkins builds triggered? Are they integrated with Github so that you see test results in the PR?

**Comment by mr-c** [comment]
Jenkins, ok to test

**Comment by mr-c** [comment]
They are integrated with GitHub, yep! Building now.

**Comment by mr-c** [comment]
@moorepants To trigger another build just push another commit to your branch

**Comment by bocajnotnef** [comment]
@moorepants Status on this?

**Comment by bocajnotnef** [comment]
ok to test

**Pull request closed without merging**
