### PR TITLE
Changes upstreamed while packaging `libkhmer` for Debian

### PR DESCRIPTION
**Pull request by kdm9**
Misc changes @mr-c & I though should be upstreamed

### CODE REVIEW

**Comment by mr-c** [comment]
@kdmurray91 I'm going to leave feedback on the Debian packaging here, for lack of better place

Since we haven't published the release candidate on GitHub you can't use `uscan` to download & exclude files & repack.

Looks like the way to work around that is:

```
wget https://github.com/dib-lab/khmer/archive/v2.0-rc1.tar.gz
mk-origtargz v2.0-rc1.tar.gz --repack --compression xz --version 2.0rc1+dfsg-1
```

& update the ChangeLog to use the matching version (with 'dfdg' in it)

`debian/control`: Should build-depend on python3-screed (>= 0.9,<< 1.0); strip out other python(2) and replace with python3.

Why liboxli**2** ?

`debian/rules`: remove "export PYBUILD_AFTER_INSTALL" paragraph as that has been fixed in 2.0

Don't add/change files directly to the upstream (khmer) code. Add them using quilt :-)

**Comment by mr-c** [comment]
Feel free to bring your commits into the `master` branch.

**Comment by mr-c** [comment]
Seems fine to me; as I don't personally use that Makefile I'm happy to leave it up to you, @Blahah, and @luizirber

**Comment by mr-c** [comment]
Checklist?

**Comment by kdmurray91** [comment]
- [ ] Is it mergeable?
- [ ] Did it pass the tests?
- [ ] If it introduces new functionality in scripts/ is it tested?
  Check for code coverage with `make clean diff-cover`
- [ ] Is it well formatted? Look at `make pep8`, `make diff_pylint_report`,
  `make cppcheck`, and `make doc` output. Use `make format` and manual
  fixing as needed.
- [ ] Did it change the command-line interface? Only additions are allowed
  without a major version increment. Changing file formats also requires a
  major version number increment.
- [ ] Is it documented in the ChangeLog?
  http://en.wikipedia.org/wiki/Changelog#Format
- [ ] Was a spellchecker run on the source code and documentation after
  changes were made?
- [ ] Is the Copyright year up to date?

**Comment by kdmurray91** [comment]
Ready for review @mr-c et al.

**Comment by mr-c** [comment]
LGTM, thanks!

**Pull request merged**
