### PR TITLE
Removed --force argument from script

### PR DESCRIPTION
**Pull request by souravsingh**
Removed the --force argument from abundance-dist-single.py

### CODE REVIEW

**Comment by ctb** [comment]
hi @souravsingh is this in relation to an issue? Also note that there are conflicts in the PR - did you start from the latest master branch? thx!

**Comment by souravsingh** [comment]
The PR is related to Issue #99.As for the conflicts,I used the latest master branch for this PR.I need to check again.

**Comment by ctb** [comment]
(I fixed the issue number to be #994.)

Please try running:

    git pull origin master

and then push that branch back to your gh repo ;).

Also, you should add a ChangeLog entry and check off all the other things on the checklist; then we can review your PR!

http://khmer.readthedocs.org/en/latest/dev/coding-guidelines-and-review.html#checklist

**Comment by souravsingh** [comment]
I will be closing this PR since there are certain problems I am facing in tests.

**Comment by ctb** [comment]
On Fri, Jan 08, 2016 at 11:34:14AM -0800, Sourav Singh wrote:
> I will be closing this PR since there are certain problems I am facing in tests.

ok - let us know if we can help!

**Pull request closed without merging**
