### PR TITLE
[MRG] Drop __future__ imports

### PR DESCRIPTION
**Pull request by standage**
Now that we've dropped Python 2 support, `__future__` imports are unnecessary. Aside from the Makefile, all changes to the code in this PR were made by `grep -v` and shell for loops.

NB: Splitting this out from #1774 to simplify code review.

- [x] Is it mergeable?
- [x] `make test` Did it pass the tests?
- [x] `make clean diff-cover` If it introduces new functionality in
  `scripts/` is it tested?
- [x] `make format diff_pylint_report cppcheck doc pydocstyle` Is it well
  formatted?
- [x] For substantial changes or changes to the command-line interface, is it
  documented in `CHANGELOG.md`? See [keepachangelog](http://keepachangelog.com/)
  for more details.

### CODE REVIEW

**Comment by standage** [comment]
I'll handle merging this back into #1774, including conflicts if there are any.

**Comment by standage** [comment]
Ready for review @ctb @luizirber @betatim!

**Comment by betatim** [comment]
Before I hit merge, do you want to merge this into master or #1774? The PR says master but your comment makes me wonder.

**Comment by standage** [comment]
Definitely into master. It's a subset of changes from #1774, which I'm trying to break into smaller more manageable chunks. I'll resolve any conflicts on that branch that arise from merging this PR.

**Pull request merged**
