### PR TITLE
[MRG] "consume_masked" mode for consume_seqfile_with_mask

### PR DESCRIPTION
**Pull request by standage**
In branch `feature/mask-comp` I implemented a new `complement` option for the `consume_seqfile_with_mask` method. By default, the function will not count any k-mers present in the mask, but with `complement=True` the function will count *only* the k-mers present in the mask/filter.

In that branch I also putzed around with some Python code (utils and scripts) to get that functionality working in `abundance-dist-single.py`.

This PR splits the C++/Cython changes from the Python changes, the latter of which aren't ready for review yet. The C++/Cython functionality is blocking my progress on a feature in kevlar, whereas I don't have a pressing need to bake this in to khmer scripts at the moment.

- [x] Is any new functionality in tested? (This can be checked with
      `make clean diff-cover` or the CodeCov report that is automatically
      generated following a successful CI build.)
- [x] Was a spellchecker run on the source code and documentation after
      changes were made?

### CODE REVIEW

**Comment by ctb** [comment]
Hi @standage the code looks good but I am not sure why you chose `complement` here. I can't find a definition of the word that makes sense with the usage here - help?

**Comment by standage** [comment]
I explained this briefly in the first paragraph of the PR, but I am open to using different terminology for the variable names if it communicates intent more clearly.

The old behavior of `consume_seqfile_with_mask` is IMO pretty self explanatory: consume all k-mers except those in the mask. The new behavior is an option that complements this behavior, consuming all k-mers that *are* in the mask.

Let me know what you think regarding terminology.

**Comment by ctb** [comment]
I finally remembered to search for "set complement" and that is the right definition :). Glad I found it! What about `consume_masked=True|False` (False by default)?

**Comment by standage** [comment]
> What about `consume_masked=True|False` (False by default)?

Roger that. I like it.

**Comment by standage** [comment]
Thank *you*

**Pull request merged**
