### PR TITLE
Fix stamps example and add it to travis runs

### PR DESCRIPTION
**Pull request by betatim**
A proposal for #1514

Seems pretty straight forward and a good test of sticking to the CLI API. Let's see how much it increases the travis run time.

- [x] Is it mergeable?
- [x] `make test` Did it pass the tests?

### CODE REVIEW

**Comment by betatim** [comment]
Increases the time for a linux build to run to about 9min. What do people think? Is it worth it?

(Clean it up a bit so that we don't see all that output from its run)

**Comment by standage** [comment]
Well, given that we were waiting 2hrs for the OS X VMs to become available at peak time this afternoon, 9 additional minutes hardly seems a big ask.

**Comment by betatim** [comment]
I edited `do.sh` so "make it pass" and didn't spend any time trying to think about whether what it is (now) doing makes sense from a science perspective. Would be good if someone could take a look.

**Comment by standage** [comment]
I'll let you update this one @betatim since it's on your fork.

**Comment by betatim** [comment]
Ready for review  @standage

**Pull request merged**
